### ISSUE TITLE
Mappable lock guards

### ISSUE THREAD

**Issue by Ogeon** [Amanieu/parking_lot#10]
Would it be possible to implement a `map` method on (some of) the lock guards? There [has been talks](https://github.com/rust-lang/rust/issues/27746#issuecomment-180284718) about it being unsound for some implementations of `Mutex`, particularly the one in the standard library, but there are ways to do it and it's a very useful feature. Do you think it would work with your particular implementation?

**Comment by Amanieu** [comment]
Unfortunately, the safety hole with `Condvar` still applies to my implementation. It's a fundamental limitation of the interface.

It might be possible to implement this using a separate `MappableMutexGuard` type which wraps a `MutexGuard` and prevents it from being used with a `Condvar`, but I'm not sure if the lifetimes work out.

**Comment by Ogeon** [comment]
That's too bad, but I suppose a `MappeableMutexGuard` wouldn't be too bad if the lifetime works out. It's how it's done in https://github.com/reem/rust-shared-mutex, possibly for a similar reason. I know practically nothing about this, myself, which is why I'm asking, but it would be cool to have.

I have this scenario where I want quite fast access to data that I want to transform before returning it, to avoid excessive dynamic checks. It would be nice to have a lock that is as light as possible, since I'll probably have to double lock my data structure (once for the whole structure and then for occasional inner mutability of each containing item). I don't think there's a way around that, since the inner mutability is basically a feature, and the function that uses it takes `&mut self` to prevent it from being called more than once.

Anyway, this is just me wishing I could just pick features from different libraries :smile:

**Comment by Amanieu** [comment]
Well it does sound like a nice feature to have, so I'll look into implementing it in parking_lot at some point.

**Comment by Ogeon** [comment]
That would be great :+1: My my actual usecase isn't really the best motivation, since my runtime check may actually be unnoticeably cheap (and hopefully optimized to oblivion), but it's also about convenience, since it's just the beginning of the pipeline. Users may want to keep on mapping.

I'll see what I can do in the meantime. Thanks for looking into it!

**Comment by Amanieu** [comment]
Have you considered using [owning_ref](http://kimundi.github.io/owning-ref-rs/owning_ref/index.html#references-into-raii-locks) for this?

**Comment by Ogeon** [comment]
I hadn't actually, but it looks like it fulfills my needs. I'll give it a try. Thanks!
