### ISSUE TITLE
Implement HLE-aware RwLock in C/direct ASM so it can be used from stable

### ISSUE THREAD

**Issue by spacejam** [Amanieu/parking_lot#100]
Have you considered implementing the asm-backed functionality in [elision.rs](https://github.com/Amanieu/parking_lot/blob/c3ae283e59bcd5010e5420ef2678bdffeec82b03/src/elision.rs#L65) via something other than Rust, built from a `build.rs` script and linking to it from stable (perhaps behind a feature) ?

**Comment by Amanieu** [comment]
I think that you would be better off keeping the existing inline fast path without lock elision than calling out to an asm function.
