### ISSUE TITLE
Return bool from `Condvar::notify*`

### ISSUE THREAD

**Issue by torkleyy** [Amanieu/parking_lot#104]
From what I see, the methods could easily indicate whether somebody was waiting on the `Condvar`. Would you mind a PR for this?

**Comment by Amanieu** [comment]
Sure! I can't see any downsides. For `notify_all`, should we return the number of threads that were notified?

**Comment by torkleyy** [comment]
Sounds like a good idea, yes!

The only drawback here is that this causes (minor) breakage.
