### ISSUE TITLE
Debug on MutexGuard

### ISSUE THREAD

**Issue by MOZGIII** [Amanieu/parking_lot#128]
Please add `Debug` for `MutexGuard`.

**Comment by Amanieu** [comment]
It should already be there?

**Comment by MOZGIII** [comment]
What do you mean? `Debug` is not implemented according to the docs: https://docs.rs/lock_api/0.1.5/lock_api/struct.MutexGuard.html

I've just had to manually call `.deref` on the guard to print the value in the debug mode. It doesn't deref automatically as there're no method calls on the value when it's printed: `print!("{:?}", my_locked_guard)` is rejected by the compiler.

**Comment by Amanieu** [comment]
Ah my bad. It seems that `Debug` is available in master, but that version has not been published yet. We are waiting for #119 to land before publishing a new release.

**Comment by MOZGIII** [comment]
I see there's active work going on there, so that's ok. But if it slows down or is paused, please consider a new release without waiting on it. Thanks!
