### ISSUE TITLE
Heap memory regression between 0.6 and 0.8

### ISSUE THREAD

**Issue by kvark** [Amanieu/parking_lot#143]
There appears to be a [memory regression](https://bugzilla.mozilla.org/show_bug.cgi?id=1554139#c0) on update from parking_lot 0.6 to 0.8, among other things. It's not proven to be "parking_lot" specifically, but perhaps anyone has ideas on what changed here that would cause more heap memory to be allocated?

**Comment by Amanieu** [comment]
The only memory that parking_lot allocates is the global hash table, which is proportional to the number of threads in the process. The allocation behavior has not changed since the earliest versions of parking_lot, so I doubt this is the direct cause.

**Comment by Amanieu** [comment]
Also, even in a process with a hundred threads, I would expect this allocation to be on the order of 10KB, which should be insignificant.

**Comment by kvark** [comment]
Ok, thanks for the quick response! I'll look for memory regression in "rand" then.
