### ISSUE TITLE
should parking_lot::rwLock implement UnwindSafe trait?

### ISSUE THREAD

**Issue by skjortan23** [Amanieu/parking_lot#145]
While porting some code that std::sync::RwLock to use parking_lots equivalent I get the following error.

`std::cell::UnsafeCell<shared_state::Shared>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary

I get this since I am using it with a state middleware in a web platform (Gotham).

Looking at the std::sync implementation in 
https://doc.rust-lang.org/std/sync/struct.RwLock.html

I see that it implements: impl<T: ?Sized> UnwindSafe for RwLock<T>

While this is currently not the case for parking_lot
Should this be the case for parking_lot as well?

**Comment by Amanieu** [comment]
See #32.

> We don't implement these traits because the `parking_lot` mutex implementation does not support poisoning. This is intentional since it allows the API to be a lot simpler and it also avoids performance issues with thread-local storage accesses.
> 
> Since the lock doesn't get poisoned by unwinding, we can't claim to be unwind-safe. However you can avoid the need for this trait by using [AssertUnwindSafe](https://doc.rust-lang.org/std/panic/struct.AssertUnwindSafe.html) from the standard library.
