### ISSUE TITLE
Confusing example for condvar

### ISSUE THREAD

**Issue by nico-abram** [Amanieu/parking_lot#152]
The condvar [docs](https://docs.rs/parking_lot/0.8.0/parking_lot/struct.Condvar.html) mention
 - No spurious wakeups
However, the [example](https://docs.rs/parking_lot/0.8.0/parking_lot/struct.Condvar.html#examples) uses a while instead of an in when wait()ing. Which is right?

**Comment by BGluth** [comment]
Yes I found this particularly confusing as well, as from my understanding there is no point to have it in a loop as well.
