### ISSUE TITLE
Feature request: `sort_key(&self) -> usize` for lock ordering

### ISSUE THREAD

**Issue by ckaran** [Amanieu/parking_lot#153]
Start by reading [this thread](https://internals.rust-lang.org/t/idea-std-sort-key-self-usize-for-lock-ordering/10382).

I know that the idea is incomplete, and as such it isn't ready for either an RFC or inclusion in the standard library.  So my question is, would you be willing to help design a better API, and maybe even include it in `parking_lot` to see how well it works?

**Comment by Amanieu** [comment]
I don't really think this belong in parking_lot itself. As sfackler said in the linked thread, you can easily do this in your own library.

**Comment by ckaran** [comment]
See my reply to sfackler on that thread.  Put simply, how do you get `Arc<Mutex<_>>` to work correctly?

**Comment by ckaran** [comment]
@CAD97 Actually came up with better code in the other thread.  Reposting here in case anyone comes searching:

```rust
use std::sync::{Arc, Mutex};

#[inline]
fn pointer_as_usize<T>(p: *const T) -> usize {
    p as usize
}

fn main() {
    let my_mutex = Mutex::new(3);
    let my_mutex_ptr: *const Mutex<usize> = &my_mutex;
    let my_other_mutex_ptr = pointer_as_usize(&my_mutex);
    println!("my_mutex_ptr       = {:?}", my_mutex_ptr);
    println!("my_other_mutex_ptr = 0x{:x?}", my_other_mutex_ptr);

    let shared_mutex = Arc::new(my_mutex);
    {
        let borrowed_ptr: *const Mutex<usize> = &*shared_mutex;
        println!("borrowed_ptr   = {:?}", borrowed_ptr);
        println!("borrowed_ptr 2 = 0x{:x?}", pointer_as_usize(&*shared_mutex));
    }

    let shared_mutex_2 = shared_mutex.clone();
    {
        let borrowed_ptr: *const Mutex<usize> = &*shared_mutex_2;
        println!("borrowed_ptr   = {:?}", borrowed_ptr);
        println!("borrowed_ptr 2 = 0x{:x?}", pointer_as_usize(&*shared_mutex));
    }
}
```

Based on the fact that his suggestion is utterly trivial to implement, I humbly withdraw this feature request.
