### ISSUE TITLE
parking_lot 0.8.1 is technically a semver breaking release

### ISSUE THREAD

**Issue by matklad** [Amanieu/parking_lot#156]
0.8.1 bumped lock_api version from `0.2` to `0.3` and, because it is a public dependency, it is a breaking change. 

See https://github.com/matklad/once_cell/issues/26

I'm personally fine with just fixing `once_cell`, but, if we want to follow semver strictly, we probably should yank `0.8.1` and publish `0.9` instead.

**Comment by Amanieu** [comment]
I yanked 0.8.1, sorry about that.
