### ISSUE TITLE
Make read_guard and write_guard public

### ISSUE THREAD

**Issue by svenknobloch** [Amanieu/parking_lot#157]
The lock_api internals uses the unsafe `read_guard` and `write_guard` function internally to create the guards if a lock can be guaranteed. I have a use case where there are locks on rows and columns of a matrix, which overlap. If the column is locked, it is safe to access the row entries for that column and vice versa. It would be nice to be able to unsafely get a reference/pointer to the underlying value in the public api.

I can also submit a PR if that makes it easier.

**Comment by svenknobloch** [comment]
If added, it would also make sense to make the `Mutex` version public as well/

**Comment by Amanieu** [comment]
These are internal helper functions and are not intended to be public.

Regarding your use case, can you instead use a combination of cloning (for read guards) and `map`?

**Comment by svenknobloch** [comment]
The issue lies in the fact that I have 2 separate locks that logically refer to the same object but only one can actually contain the object. I have a custom coarse lock that determines which of those 2 locks has to be active to guarantee safety and then can access the object, which means one of the locks needs to unsafely access the value inside the other. I could implement it with reference counting, but would like to avoid the overhead of having to use more heap memory and allocations.

Would you be open to adding an unsafe `get` method that calls the underlying `UnsafeCell::get` to return a `*mut T`?

**Comment by Amanieu** [comment]
I think that your use case may be sufficiently complicated that it might be easier to just write your own lock wrapper based on `RawMutex` or `RawRwLock`.

**Comment by svenknobloch** [comment]
That might work as well. I'll take a look, thanks!
