### ISSUE TITLE
Usage of hardware lock ellision breaks rr.

### ISSUE THREAD

**Issue by emilio** [Amanieu/parking_lot#16]
Hi @Amanieu,

This issue is just to ping you about https://github.com/mozilla/rr/issues/1883.

Basically we were hitting this in Servo, and I thought that other people that could be using `rr` to debug programs that use `parking_lot` would encounter this.

Basically, HLE makes rr break right now. Probably a runtime check for `RUNNING_UNDER_RR` is prohibitive (maybe under `debug_assertions` it isn't?). In any case, maybe a note in the Readme or similar could help someone.

Anyway, feel free to close this at any time, thanks!

 -- Emilio

**Comment by Amanieu** [comment]
Would a cargo feature to disable lock elision help?

**Comment by rocallahan** [comment]
That would be good.

I should mention though, that I may have figured out a way to fix this in rr. Maybe. I'll let you know :-).

**Comment by rocallahan** [comment]
Yeah, we figured out how to fix this in rr. Sorry for the noise! Please close.
