### ISSUE TITLE
CondVar with RwLock

### ISSUE THREAD

**Issue by gyscos** [Amanieu/parking_lot#165]
Hi!
I'd like to have multiple readers wait until the right value is written.
One solution would be to have a `CondVar` based on a `RwLock` rather than a `Mutex`.
This seems to be what another crate is doing: https://docs.rs/shared-mutex/0.3.1/shared_mutex/struct.SharedMutex.html

Could something similar be added to parking_lot?

Thanks!

**Comment by Amanieu** [comment]
You can easily implement a `Condvar` that accepts any type of guard like this:
```rust
struct CondvarAny {
    c: Condvar,
    m: Mutex<()>,
}
impl CondvarAny {
    fn wait<T>(&self, g: &mut RwLockReadGuard<'_, T>) {
        let guard = self.m.lock();
        RwLockReadGuard::unlocked(g, || {
            // Move the guard in so it gets unlocked before we re-lock g
            let mut guard = guard;
            self.c.wait(&mut guard);
        });
    }
}
```
The current `Condvar` implementation in `parking_lot` is deeply tied to the internals of `Mutex`, so a completely new `Condvar` implementation would be required to support `RwLock`.

**Comment by gyscos** [comment]
Oh sweet, thanks! Hadn't used `RwLockReadGuard::unlocked` yet, this looks perfect.
I guess the main difference with a new `CondVar` designed specifically for `RwLock` would be slightly higher performance, but I'll run some benchmarks - this `CondVarAny` is probably fine as-is.
Thanks again!

**Comment by EFanZh** [comment]
> You can easily implement a `Condvar` that accepts any type of guard like this:

Hi @Amanieu: I found that in order for the corresponding `notify_once` and `notify_all` to work, I have to lock the `Mutex` at least once before calling `notify_once` and `notify_all`:

```rust
impl CondvarAny {
    fn notify_one(&self) {
        drop(self.m.lock());

        self.c.notify_one();
    }

    fn notify_all(&self) {
        drop(self.m.lock());

        self.c.notify_all();
    }
}
```

Otherwise notification for updates can get lost, causing deadlock, see [this example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b4dd6f28fe1f7fafad3b989e6ff5fc34). Maybe it is worth mentioning this in your original comment?

**Comment by Amanieu** [comment]
You are correct! The inner mutex needs to be held when notifying otherwise you may miss wakeups. I've updated my code.

**Comment by EFanZh** [comment]
@Amanieu: Also, I suspect that we don’t need to actually hold the lock while calling `notify_one` and `notify_all`. Lock and release once before calling `notify_one` and `notify_all` seems to be enough?
