### ISSUE TITLE
Creating raw locks directly

### ISSUE THREAD

**Issue by drewhk** [Amanieu/parking_lot#178]
I saw this ticket, but it does not seem to answer my question: https://github.com/Amanieu/parking_lot/issues/68

I need a lock to manage critical sections that involve an external process (via HTTP actually). In this case I am not really concerned about memory safety as there is no shared memory involved at all, I just need to ensure certain consistency properties that has nothing to do with memory. As far as I see, the raw locks themselves are completely safe as they themselves do not give shared access to any memory location.

Is there any reason why these raw locks could not be created for such use cases? Right now I had to use an `RwLock<()>` and then get to the raw lock by `unsafe fn raw()`, which is adding unsafe code to a place where I see no unsafety... Also, in my use case the `guard` approach does not work very well as I am coordinating between async streams and repeating tasks and it is really hard to propagate the guards to all the right places (I am not sure if they are `Send` even...), so in my use case an `Arc<RawRwLock>` would be ideal.

Do you think it is possible exposing these raw locks? Or do you see dangers here that I am simply unaware of?

**Comment by faern** [comment]
The raw locks are exposed directly since release `0.7.0`: https://docs.rs/parking_lot/0.9.0/parking_lot/struct.RawMutex.html

> I am coordinating between async streams ..

I don't know your use case exactly. But you probably don't want to do any parking lot operations (parking threads!) in an async context. As that would pause the entire OS thread, and not allow the async runtime/executor to process other tasks on that thread while your task waits for the lock.

**Comment by drewhk** [comment]
> The raw locks are exposed directly since release 0.7.0: https://docs.rs/parking_lot/0.9.0/parking_lot/struct.RawMutex.html

Yes, but you cannot create them directly...

> But you probably don't want to do any parking lot operations (parking threads!) in an async context. As that would pause the entire OS thread, and not allow the async runtime/executor to process other tasks on that thread while your task waits for the lock.

I am aware of this, and it is handled properly in my scenario (readers do not block but back off simply, and the writer delegates the blocking to a dedicated "sacrificial" thread). I mean, in my case this could be implemented totally lockless, but given the low-frequency nature of my problem (it is a garbage collection of some sort) wrangling with atomics directly (and `unsafe`) this seemed like a dumb but safe option.

**Comment by Amanieu** [comment]
You can use `RawMutex::INIT` to create a raw lock.

**Comment by drewhk** [comment]
AAAh, sorry I missed that totally! Thank you guys!
