### ISSUE TITLE
Deadlock detection

### ISSUE THREAD

**Issue by arthurprs** [Amanieu/parking_lot#18]
How hard would it be to detect deadlocks and other types of "runtime bugs" in debug mode?

**Comment by arthurprs** [comment]
This is interesting stuff. I guess that sort of instrumentation would also make possible to detect deadlocks due to poisoned locks as well.

**Comment by Amanieu** [comment]
Poisoning is a different issue from deadlock detection: it's just a bit that you set in the `MutexGuard` destructor when panicking so that any future attempts to lock the mutex panic as well.

**Comment by Amanieu** [comment]
I think this could be implemented as an additional feature on top of `ReentrantMutex`. We could have `lock` return an enum which indicates whether this is the first lock for the current thread. Deadlock detection could then be done by simply asserting that a recursive lock is never taken.

**Comment by arthurprs** [comment]
That's one case, but I guess the most common one is like:

Thread 1 locks A, Thread 2 locks B
Thread 2 attempts to lock B and thread 2 attempts to lock A

**Comment by Amanieu** [comment]
Unfortunately situations like that are much more difficult to detect. You would need a tool like [Hellgrind](http://valgrind.org/docs/manual/hg-manual.html).

**Comment by arthurprs** [comment]
Just pointing it out. Maybe it's just better to leave it out to avoid confusion.

**Comment by arthurprs** [comment]
Closed via #39
