### ISSUE TITLE
Reentrant locks

### ISSUE THREAD

**Issue by arthurprs** [Amanieu/parking_lot#19]
It would be interesting to have these as separated types.

**Comment by Amanieu** [comment]
These are pretty simple to implement. The only downside is that it adds a dependency on the `thread_id` crate. I don't think this is too much of an issue in practice though.

**Comment by ticki** [comment]
Hmm, this would actually be really nice. There isn't a good reentrant mutex library so far.

**Comment by shisoft** [comment]
I was thinking about that too, just not sure how to implement when there should no more than one mut reference to the value.

**Comment by ticki** [comment]
@shisoft Just disable `Send` on the guard, I suppose.

**Comment by shisoft** [comment]
@ticki It should not be that easy. The guards use a reference to a UnsafeCell in the lock. According to the documents for UnsafeCell, it required to ensure 'no two mutable references obtained'
https://doc.rust-lang.org/std/cell/struct.UnsafeCell.html

Which means there should be no more than one mutable guard. Am I correct?

**Comment by Amanieu** [comment]
Added in parking_lot 0.3.7.

**Comment by shisoft** [comment]
Wow, that was fast. But I was expecting ReentrantRwLock though.
Never mind, I know what to do.

**Comment by Amanieu** [comment]
The thing with reentrant locks is that you can only give out shared references, not mutable ones, because otherwise you would end up with mutable `&mut` pointing to the same data.

**Comment by Amanieu** [comment]
With that in mind, a `ReentrantRwLock` is exactly the same thing as taking a read lock on a normal `RwLock`.

(also, I'm not *that* fast, I had most of the code for this already written. I just polished it up a bit and pushed it.)

**Comment by shisoft** [comment]
Yes, that is what I was thought about. In java, there is a [ReentrantReadWriteLock](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantReadWriteLock.html), without reference to the data it is protecting. The re-entrant RwLock means the write lock will not block each other in the same thread but share the same reference. I think it is not possible to implement this safely in rust. If there is no reference in the lock, there should still be a way, but off-topic.
