### ISSUE TITLE
New release with smallvec 1.0?

### ISSUE THREAD

**Issue by kjeremy** [Amanieu/parking_lot#190]
Can we get a new release with #188?

**Comment by faern** [comment]
This is a breaking change. So we should see if there is anything else valuable in the pipeline to merged/do first. We are currently working on adding more tests to various aspects of this crate. Would be nice to get that done first. In case the tests show any issues, it would be nice to have them fixed before a new major release.

And I see we have some documentation to update. For example, `Mutex` and `Once` is now 1 byte even on stable. It has been for a while, but the docs don't reflect that.

**Comment by Manishearth** [comment]
I think the ecosystem is slowly moving to smallvec 1.0 so we should perhaps cut this release as soon as we can.

**Comment by faern** [comment]
Ok. Some tests are merged and no problems found so far. Unless @Amanieu has some other plans, maybe we can try publishing a release this weekend.

**Comment by faern** [comment]
`parking_lot 0.10.0` along with `parking_lot_core 0.7.0` and `lock_api 0.3.2` has been published! Closing this.

**Comment by Manishearth** [comment]
Thank you!
