### ISSUE TITLE
Sendable guards

### ISSUE THREAD

**Issue by arthurprs** [Amanieu/parking_lot#197]
> The deadlock detection code (which can be enabled through a feature) will break if a mutex can be unlocked in a different thread than the one that locked it. It was decided that disabling `MutexGuard: Send` if that feature is enabled would be unacceptable since it might break code that relies on `MutexGuard: Send`.

_Originally posted by @Amanieu in https://github.com/Amanieu/parking_lot/issues/139#issuecomment-490236259_

While I understand the reasoning in the quote above, it's not ideal. This a bit weird for me to say, considering I proposed and implemented the PR that introduced the deadlock detection :rofl: 

Parkinglot is the **only** crate that _can/could_ do Sendable guard AFAIK. So maybe should try to  preserve it somehow?

Sendable guards may come in handy, as it just did for me, and you'd have to use an unsafe impl to work around it and hope that nobody enables deadlock detection.

Some ideas, each with its own {up/down}sides
1 - Reintroduce Sendable guards which is implicitly a `!deadlock` feature.
2 - Create a Sendable{Mutex,RwLock} or something like that that don't participate in the deadlock detection.
3 - Same as above, but in another crate.
4 - ..

**Comment by nerdrew** [comment]
Just ran into needing this too. Sendable guards would be nice in an async/await world.

**Comment by wchargin** [comment]
Pardon the naïve question: in rust-lang/rust#23465, @alexcrichton notes
that the stdlib guards are intentionally `!Send` because [the pthread
interface specifies][pt] that it is undefined behavior if “a thread
attempts to unlock a mutex that it has not locked”.

Is this a non-issue for `parking_lot` simply because it doesn’t use
libpthread or the pthread APIs at all, and instead implements its locks
from scratch, directly on top of atomics?

[pt]: https://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_mutex_lock.html

**Comment by faern** [comment]
`parking_lot` still uses pthread mutexes under the hood for the actual thread parking on systems that does not support a more efficient thread parking method. See https://github.com/Amanieu/parking_lot/blob/master/core/src/thread_parker/unix.rs

**Comment by Amanieu** [comment]
It isn't a concern for `parking_lot` because we implement our own locks. The internal thread parker that uses pthread doesn't impact this since *that* lock is not sent between threads.

**Comment by U007D** [comment]
FYI, I have also run into a use case looking for `Send`able `Guard`s.  It's not clear to me from reading this (and linked) issues if there is a workaround?

AFAIAA, I am fine to work without the deadlock detection feature (I didn't know it was there, actually).

**Comment by Amanieu** [comment]
You need to enable the `send_guard` feature on the `parking_lot` crate.

**Comment by U007D** [comment]
Thank you!
