### ISSUE TITLE
RwLockReadGuard::bump is unsound

### ISSUE THREAD

**Issue by pitdicker** [Amanieu/parking_lot#199]
The following methods are unsound because they can lead to aliasing mutable references:
```
RwLockReadGuard::bump
RwLockReadGuard::unlocked
RwLockReadGuard::unlocked_fair
ReentrantMutexGuard::bump
ReentrantMutexGuard::unlocked
ReentrantMutexGuard::unlocked_fair
```

Example:
```rust
use parking_lot::{RwLock, RwLockReadGuard};

fn main() {
    let lock = RwLock::new(10u32);
    let mut ref1 = lock.read();
    let ref2 = lock.read();
    let bare_ref: &u32 = &*ref2;
    RwLockReadGuard::bump(&mut ref1);
    // Another thread can now acquire a mutable reference to the RwLock while
    // we hold a shared reference.
    assert_eq!(*ref1, *bare_ref);
}
```

Note that without these methods `RwLockReadGuard::map` doesn't have to return a seperate type, but can just return an `RwLockReadGuard`, and the same is true for `ReentrantMutexGuard::map`.

Discovered (with a better explanation) in https://pitdicker.github.io/Creative-methods-on-interior-mutability-types/#temporary-lending-out-from-a-smart-pointer.

**Comment by pitdicker** [comment]
Although not part of `parking_lot`, I suppose that also makes https://github.com/Amanieu/parking_lot/issues/165 unsound if a `Condvar` is combined with `RwLockReadGuard`.

**Comment by Amanieu** [comment]
I don't think this is unsound: these methods only release a single lock guard, not the entire lock. This means that in your example, the rwlock is never unlocked since `ref2` still holds a read lock. `bump` and `unlocked` have no effect if the reference count is not 1.

**Comment by pitdicker** [comment]
Apologies for not checking better, you are right.
