### ISSUE TITLE
Why no RwLockReadGuard::upgrade?

### ISSUE THREAD

**Issue by pitdicker** [Amanieu/parking_lot#200]
Let me ask a question first, before writing something ignorant again ;-).

I am curious why there is a separate `RwLockUpgradableReadGuard` type. Why can't `RwLockReadGuard` have an `upgrade` method?
Is it just to prevent a possible deadlock in `upgrade`, because there may be multiple instances of `RwLockReadGuard` in one thread?

If that is the reason, is it not mostly moving around the problem?
- Getting an `RwLockWriteGuard` (which can be downgraded to `RwLockUpgradableReadGuard`) can deadlock if the thread already has a write or read lock.
- Getting an `RwLockUpgradableReadGuard` can deadlock if the thread already has a write or read lock.
- Getting a read lock can deadlock if the thread already has an `RwLockUpgradableReadGuard` or `RwLockWriteGuard`.

Or is there a more fundamental reason?

**Comment by Amanieu** [comment]
No, the main issue here is if there are 2 threads with a read lock each and they both try to upgrade, you will end up with a deadlock because they are each waiting for the other to release their read lock. This is why only one upgradable lock is allowed at any time.

**Comment by pitdicker** [comment]
O, I thought there could only be one `RwLockUpgradableReadGuard` per thread. Something to think about, but thank you again!

**Comment by jnicholls** [comment]
Sorry to resuscitate this issue after it's been closed, but I'm looking for some clarity. According to the documentation, there can only be one thread that holds a `RwLockUpgradableReadGuard`. If that is the case, what purpose does it even serve? That's no more advantageous than taking out a `RwLockWriteGuard`?

> The calling thread will be blocked until there are no more writers or other upgradable reads which hold the lock.

**Comment by bjorn3** [comment]
> The expectation is that multiple threads can hold an upgradable read lock, and when one of them decides they must acquire an exclusive write lock, they upgrade the lock. I am not understanding what use case this upgradable read lock is solving if only one thread can hold it in read mode at a time. Thank you in advance for the clarification!

It is useful when you have reads for which you know that it won't ever be upgraded, but one which may be upgraded.
