### ISSUE TITLE
Upgrading a `RwLockReadGuard` to `RwLockWriteGuard` without dropping the lock.

### ISSUE THREAD

**Issue by ticki** [Amanieu/parking_lot#21]
A function like `.upgrade()`.

**Comment by Amanieu** [comment]
The problem with upgradable rwlocks is that they are very prone to deadlocks: consider the case where two reader threads both try to upgrade without dropping the lock.

While this could be supported by creating a third type of lock guard (`RwLockUpgradeGuard`) which allows concurrent readers but block writers and other upgradable locks, this significantly complicates the implementation.

**Comment by ohanar** [comment]
Should this be closed now?

**Comment by Amanieu** [comment]
Yes.
