### ISSUE TITLE
found odd virus

### ISSUE THREAD

**Issue by Lightnet** [Amanieu/parking_lot#213]
I am using avast scan and found win32:Evo-gen. I did build compile.

Window 10 64 Bit.

Found in >
  https://github.com/PistonDevelopers/dyon 

Tested simple example. Virus scan pop up.

I was doing fresh install OS window 10 build clean. But it didn't found on old machine. But it did slow down my pc and not response correctly(lag delay longer).

**Comment by Amanieu** [comment]
I don't think this has anything to do with parking_lot?

**Comment by bjorn3** [comment]
win32:Evogen is a heuristic to detect applications which behave in a suspicious way. It doesn't mean that the application in question is actually malicious. Heuristics are just meant to detect unknown malware at the cost of false-positives once in a while. You may want to submit the applications for further inspection. (maybe there is a button in the quarantine menu)
