### ISSUE TITLE
lock_api: Add `Spinlock` types?

### ISSUE THREAD

**Issue by phil-opp** [Amanieu/parking_lot#214]
The documentation contains an [example spinlock implementation](https://docs.rs/lock_api/0.3.3/lock_api/#example), which is very useful for `no_std` applications. Have you thought about adding the `RawSpinlock` type (and maybe also the `Spinlock`/`SpinlockGuard` aliases) to the library itself? This way, people would not need to copy&paste the implementation into their own projects.

The reason I'm opening this bug is the following: I'm currently using the [`spin`](https://docs.rs/spin/0.5.2/spin/) crate, which is no longer maintained according to the [RUSTSEC project](https://rustsec.org/advisories/RUSTSEC-2019-0031). As an alternative, they recommend `lock_api`. However, it does not provide any drop-in replacement for the `spin::Mutex` type and instead requires users to build their spinlock themselves.

**Comment by Amanieu** [comment]
Implementing a proper spinlock is much more complicated than just the basic example presented in the crate documentation. There are many different possible implementations, each with their own advantages and drawbacks:
- [Test and test-and-set spinlocks](https://en.wikipedia.org/wiki/Test_and_test-and-set)
- [Ticket spinlocks](https://lwn.net/Articles/267968/)
- [MCS spinlocks](https://lwn.net/Articles/590243/)
- etc...

I feel that this would be better suited as a separate crate which builds upon the traits provided by `lock_api`.

**Comment by phil-opp** [comment]
Makes sense, thanks for the answer!

(In case anyone is reading this thread: I'm thinking about creating such a crate. Feel free to contact me if you want to collaborate!)

**Comment by faern** [comment]
@phil-opp A suggestion: Try contacting the developer(s) of `spin` and see if you can take it over and/or become co-maintainer. Better to keep the already existing and used library up to date and working than having a myriad of similar libraries where it's hard to figure which one does what and how well they do it.

**Comment by phil-opp** [comment]
@faern While I agree that co-maintaining spin would be a good solution, it seems like a quite large task because the crate also has own implementations of `Once` and `RwLock`. A new crate based on the abstractions of `lock_api` does seem like maintainance burden.

**Comment by phil-opp** [comment]
I just published a simple `spinning_top` crate: <https://docs.rs/spinning_top/0.1.0/spinning_top/>. Comments and reviews appreciated.
