### ISSUE TITLE
Hardware transactional memory support

### ISSUE THREAD

**Issue by LifeIsStrange** [Amanieu/parking_lot#220]
Hi!

I'm not at all an expert on locking primitives ^^
But I just read about something awesome, present in all mainstream Intel cpus:
TSX 
https://en.m.wikipedia.org/wiki/Transactional_Synchronization_Extensions
It allow a 40% performance gain on memory access by using mutexes only as a fallback.
The beauty is that it offer a backward compatible API such that one hasn't to write two code paths (one for modern cpus and one for legacy).

If rust through parking_lot implement TSX support and eventually make all users of parking_lot transparently benefit from such performance gain, would be revolutionary.
It would help so much software!

**Comment by LifeIsStrange** [comment]
The implementation could, for example, use the following primitives:
https://lib.rs/crates/intel-tsx-rtm
Or 
https://docs.rs/swym-htm/0.1.0/swym_htm/

**Comment by Amanieu** [comment]
We already use TSX hardware lock elision for `RwLock`: https://github.com/Amanieu/parking_lot/blob/master/src/elision.rs

**Comment by LifeIsStrange** [comment]
Amazing!
@Amanieu what about using/exposing Restricted Transactional Memory (RTM) too?

**Comment by Amanieu** [comment]
While using HLE is a simple optimization on top of the existing `RwLock` type (we only use it for read locks since write locks tend to conflict and abort transactions), exposing RTM would require a specialized API since you wouldn't use it in the same situations as a normal `Mutex`. I feel that this is best left to another crate.

**Comment by LifeIsStrange** [comment]
Thank you for the professionalism :}

**Comment by LifeIsStrange** [comment]
@Amanieu next generation Intel CPUs will have a new TSX instruction:
https://www.phoronix.com/scan.php?page=news_item&px=Intel-PRM-Hybrid-Sapphire

> TSXLDTRK is Intel TSX Suspend Load Address Tracking and is confirmed as coming with Sapphire Rapids / Golden Cove. With that is the XSUSLDTRK to suspend tracking load addresses and XRESLDTRK so that software developers can choose the memory accesses that do not need to be tracked by a TSX (Transactional Synchronization Extensions) read set.

I wonder when that instruction should be used, do you see any use case / possible optimization for parking_lot?

**Comment by Amanieu** [comment]
I don't see any way these instructions would be useful for parking_lot. As I said before, it would be better to expose these features in a separate crate specialized for transaction memory.
