### ISSUE TITLE
Cannot find macro `llvm_asm`

### ISSUE THREAD

**Issue by imp** [Amanieu/parking_lot#225]
Since parking_lot was updated to 0.10.1 I am getting this error
```
error: cannot find macro `llvm_asm` in this scope
  --> /.../.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.10.1/src/elision.rs:77:13
   |
77 |             llvm_asm!("xacquire; lock; cmpxchgq $2, $1"
   |             ^^^^^^^^

error: cannot find macro `llvm_asm` in this scope
   --> /.../.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.10.1/src/elision.rs:108:13
    |
108 |             llvm_asm!("xrelease; lock; xaddq $2, $1"
    |             ^^^^^^^^
```

Perhaps there needs to be some guidance regarding the minimal Rust version where this macro is supported?

**Comment by Amanieu** [comment]
This only happens if you are using the `nightly` feature. You need to update your nightly Rust.

**Comment by imp** [comment]
I am having some other (unrelated) issues with the today's nightly. What is the earliest nightly that will work?

**Comment by Amanieu** [comment]
The PR (https://github.com/rust-lang/rust/pull/68404) landed on March 27, so any nightly after that.
