### ISSUE TITLE
Once<T = ()>

### ISSUE THREAD

**Issue by scottlamb** [Amanieu/parking_lot#23]
I think that typically when you want a `Once`, you're calculating a value, as in the example in the documentation. I propose `parking_lot` make it safe to do so by wrapping the value in the `Once` as `Mutex` and such do. I think defaulting the parameter to `()` would mean this wouldn't be a breaking change.

(It'd be like the [lazycell crate](https://github.com/indiv0/lazycell)'s `AtomicLazyCell` except that if thread A tries to fill the cell while thread B is already doing so, thread A will wait for thread B. lazycell returns an error in this case.)

I think this would _almost_ make it possible to lose the `unsafe` in said example:

```rust
use parking_lot::{Once, ONCE_INIT};

static VAL: Once<usize> = ONCE_INIT;  // error here :-(

// This function will only call `expensive_computation` once, and will
// otherwise always return the value returned from the first invocation.
fn get_cached_val() -> usize { VAL.call_once(expensive_computation) }

fn expensive_computation() -> usize {
    // ...
}
```

except that I don't think there can be a `ONCE_INIT` that would work for all types. So to make this work as a static for types other than `()`, it'd either have to use [const fns (unstable)](https://github.com/rust-lang/rust/issues/24111) or expose the inner workings of the type (and I guess that'd be back to unsafe anyway as there'd be an `UnsafeCell`). So for now, this would be beneficial for non-statics, potentially beneficial for nightly with statics, and no worse than before for stable rust with statics.

**Comment by scottlamb** [comment]
On the other hand, it occurs to me that at least in my use case, I want to store a `Box`, and it'd be more space-efficient to have a `parking_lot::BoxOnce<T: ?Sized>` which assumes 8-byte-aligned pointers (as returned by jemalloc), stuffs poison/locked/park into the low-order bits, and considers the itself done if the pointer is non-null. If both `BoxOnce` and `Once<T>` existed, I'd use the former over the latter.

**Comment by Amanieu** [comment]
I can't change the definition of `Once` since this will be a breaking change. Additionally, `ONCE_INIT` will no longer work on stable since `Once` will need to contain an `UnsafeCell`, which can't be statically constructed without `const fn` support.

Instead I have added a `state` method to `Once` which can tell you in a thread-safe way whether the initialization protected by a `Once` is complete. You can use this to build your own `AtomicLazyCell` type.
