### ISSUE TITLE
An is_locked API for RawMutex?

### ISSUE THREAD

**Issue by coolreader18** [Amanieu/parking_lot#232]
I'm using `parking_lot` and `lock_api` to implement the `_thread` Python module, and it works really well! The one thing that doesn't have a mirror is the `locked()` method of lock objects, which tells whether the lock is currently locked. Would it be feasible to add something like a `RawMutexStatus` trait that has an `is_locked(&self) -> bool` method, or would that not be able to be implemented for `parking_lot::RawMutex`, due to that not being a proper atomic operation or something?

**Comment by Amanieu** [comment]
You can emulate `is_locked` by calling `try_lock` and seeing if it succeeds. Don't forget to release the lock afterwards if `try_lock` succeeded.

**Comment by coolreader18** [comment]
Thank you, that seems to work.

**Comment by coolreader18** [comment]
Would it make sense then to have an `is_locked` method on the `RawMutex` trait, with a default implementation of `try_lock(); unlock()`, that can be overriden when you have a better way to do it?

**Comment by Amanieu** [comment]
Sure that sounds like a good idea. I'm happy to accept a PR for it.

**Comment by coolreader18** [comment]
Alright, I've opened #235.
