### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by azriel91** [Amanieu/parking_lot#239]
Heya, would it be alright to publish another version of `parking_lot` in the near future?

I'm mainly looking forward to the `instant::Instant` support so that my library can depend on published dependencies instead of git dependencies.

Thank you!

**Comment by Amanieu** [comment]
I'm hoping to release a new version this week. I've got a backlog of things to do for this crate.

**Comment by coolreader18** [comment]
Any updates on this?

**Comment by Amanieu** [comment]
Done
