### ISSUE TITLE
Should lock_api::RawMutex::unlock (and other unlock methods) be unsafe?

### ISSUE THREAD

**Issue by brain0** [Amanieu/parking_lot#242]
For most Mutex implementations, calling `RawMutex::unlock` without calling `RawMutex::lock` first is likely undefined behavior. The same goes for all other `unlock_*` methods. Therefore, I think that these trait methods should be unsafe.

**Comment by Amanieu** [comment]
That's a fair point, do you want to write up a PR for this?

**Comment by brain0** [comment]
Since you agree, I can look into it.

**Comment by Amanieu** [comment]
Fixed by #243
