### ISSUE TITLE
lock_api tests

### ISSUE THREAD

**Issue by cmnord** [Amanieu/parking_lot#249]
I've just written my own RWLock with `lock_api` and would like to test it. It would be nice if `lock_api` included some simple tests. Would it be possible to, for example, port the tests from `std::sync::RWLock` to `lock_api::RWLock` and automatically run them with my new RWLock?

The `lock_api` docs say "not only does [lock_api] eliminate a large portion of the work in implementing custom lock types, it also allows users to write code which is generic with regards to different lock implementations." It would be cool if basic tests were part of this 🙂

**Comment by Amanieu** [comment]
The tests can't be added to `lock_api` itself since you can't test a trait, you need to test a concrete implementation of that trait.

**Comment by cmnord** [comment]
Hm yeah, it makes sense that you can't test a trait. So there's no way to automatically run some set of tests for every concrete implementation of the trait?

**Comment by Amanieu** [comment]
I would suggest just copying the `parking_lot` tests to your crate. They were originally from libstd.

**Comment by cmnord** [comment]
Oh great, that was really easy 🙂 Thank you!
