### ISSUE TITLE
lock_api nightly feature

### ISSUE THREAD

**Issue by coolreader18** [Amanieu/parking_lot#250]
Is the `nightly` feature for `lock_api` still necessary? 1.36 has const fns, and I'm not really sure why there's a `const_mutex()` function in parking_lot but not a const constructor in lock_api; it's not like a `RawMutex` can be non-const or something, it has to have a `INIT` associated constant.

**Comment by Amanieu** [comment]
It's because there are restrictions on `const fn` functions with generic bounds, which means that those functions do not compile on stable.

**Comment by coolreader18** [comment]
Ah, gotcha, thanks.
