### ISSUE TITLE
Panic when running benchmark

### ISSUE THREAD

**Issue by nico-abram** [Amanieu/parking_lot#255]
Running the benchmark with the following command on windows 

`cargo run --release --bin rwlock -- 2 1 1 0 1 2 2>&1 > bt.txt`

Panics within what seems to be the parking_lot inside std with the message "Could not get module handle for ntdll.dll"

I'm attaching the RUST_BACKTRACE=full output

[bt.txt](https://github.com/Amanieu/parking_lot/files/5433787/bt.txt)

**Comment by cynecx** [comment]
Uff, you are using a really old version of parking_lot. Is there any reason you can't use a more recent release of parking_lot?

![image](https://user-images.githubusercontent.com/5961244/97094027-3ad2fd00-1651-11eb-85a2-6c2641512335.png)

**Comment by nico-abram** [comment]
I ran it using the master branch, I think the older version is from std

**Comment by cynecx** [comment]
Uh, your backtrace says that you are using parking_lot 0.2.8:

![image](https://user-images.githubusercontent.com/5961244/97094200-f47e9d80-1652-11eb-924a-49ce1e053d40.png)

Is this a peer dependency somehow?

**Comment by nico-abram** [comment]
Here's the output from 

`cargo tree`

![imagen](https://user-images.githubusercontent.com/24706838/97094365-ecab0300-162a-11eb-8bcb-f0dd737bf67f.png)

[tree.txt](https://github.com/Amanieu/parking_lot/files/5433839/tree.txt)

Seems to actually come from SeqLock, not std, you're right

**Comment by cynecx** [comment]
A temporary workaround would to to clone seqlock, update parking_lot, fix code and use use your clone of seqlock instead.

**Comment by nico-abram** [comment]
Yup! That seemed to do it, just updating the parking_lot in seqlock to 0.11 and patching the benchmark crate to use that fixed it (seqlock itself required no changes to compile, at least on windows)

Opened a pull request https://github.com/Amanieu/seqlock/pull/5
