### ISSUE TITLE
RwLockReadGuard and RwLockWriteGuard should only be Sync when RawRwLock is

### ISSUE THREAD

**Issue by ammaraskar** [Amanieu/parking_lot#259]
Currently `RwLockReadGuard`s are marked as `Sync` so long as the contained type is, without having the same bound on the `RawRwLock` type:

https://github.com/Amanieu/parking_lot/blob/ecfe20bf5b7f8b06c7a39afd53cee88a99ce07db/lock_api/src/rwlock.rs#L878

This means that even if an implementer marks their guard as `GuardNoSend`, it's actually possible to send guard objects across threads using references to them (references are marked as `Send` so long as the underlying type is `Sync`).

Much like `MappedMutexGuard` this should probably only be `Sync` when the raw lock is.

An example of sending `parking_lot`'s non sendable guard objects across threads:
```rust
use parking_lot::RwLock;
use crossbeam_utils::thread;

fn is_send<T: Send>(_: &T) {}

fn main() {
    let lock = RwLock::new(42);
    let read_guard = lock.read();
    // RwLockReadGuard itself is not Send-able, uncommenting
    // the line below causes a compilation failure.
    //is_send(&read_guard);
    
    thread::scope(|s| {
        let guard_ref = &read_guard;
        
        s.spawn(move |_| {
            // But they can be sent as a reference.
            let sent_lock_guard = guard_ref;
            println!("In thread: {:p}", sent_lock_guard);
        });
        println!("In main:   {:p}", &read_guard);
    });
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=625dd71fdcd34658f0c2d2752a86ca0e

(Issue found by @sslab-gatech's Rust group)

**Comment by Amanieu** [comment]
I believe this is not a problem since the only thing you can do with a `&RwLockReadGuard` is dereference it to access the underlying data. There is no interaction with the `RawRwLock` itself so it should still be sound.

**Comment by ammaraskar** [comment]
Oh right, the problem is the:

`pub fn rwlock(s: &Self) -> &'a RwLock<R, T>`

method which would allow you to get a reference to the underlying `RwLock` object, which might not itself be safe across threads.

**Comment by Amanieu** [comment]
Ah good point, I forgot about that one. I will adjust the trait bounds.
