### ISSUE TITLE
Implementing Future

### ISSUE THREAD

**Issue by ckaran** [Amanieu/parking_lot#264]
I've been spending some time thinking about how to implement [`Future`](https://doc.rust-lang.org/std/future/trait.Future.html) on mutexes, and after reading #155, #86, and #24, I agree that implementing [`Future`](https://doc.rust-lang.org/std/future/trait.Future.html) on mutexes would be difficult.  

But what about for condition variables? [`wait()`](https://docs.rs/parking_lot/0.11.1/parking_lot/struct.Condvar.html#method.wait) looks a lot like `await` to me...

**Comment by Amanieu** [comment]
This has the same problem as mutexes: you would have to change the function to return a `Future`, at which point the API changes completely. It is better to do this as a separate crate.

**Comment by ckaran** [comment]
I hadn't been thinking of changing [`wait()`](https://docs.rs/parking_lot/0.11.1/parking_lot/struct.Condvar.html#method.wait), I had been thinking of implementing [`Future`](https://doc.rust-lang.org/std/future/trait.Future.html) on [`CondVar`](https://docs.rs/parking_lot/0.11.1/parking_lot/struct.Condvar.html) such that calling [`poll()`](https://doc.rust-lang.org/std/future/trait.Future.html#tymethod.poll) on it would return [`Poll::Pending`](https://doc.rust-lang.org/std/task/enum.Poll.html#variant.Pending) until the condition variable was notified, at which point it would return [`Poll::Ready`](https://doc.rust-lang.org/std/task/enum.Poll.html#variant.Ready).

That said, I also see that I didn't read the API closely enough; even though I was reading the docs for [`wait()`](https://docs.rs/parking_lot/0.11.1/parking_lot/struct.Condvar.html#method.wait), I *still* managed to get it into my head that [`CondVar`](https://docs.rs/parking_lot/0.11.1/parking_lot/struct.Condvar.html) was created with a reference to a given mutex, which would mean that it was held internally somehow.  Without that, I don't see how it would be possible to implement [`Future`](https://doc.rust-lang.org/std/future/trait.Future.html) as there isn't a way to pass that information in.  So I agree with your assessment, and withdraw the request.
