### ISSUE TITLE
Add arc-based mutex locks to the `lock_api` crate

### ISSUE THREAD

**Issue by notgull** [Amanieu/parking_lot#273]
At the moment, mutex locks are implemented roughly as follows:

```
pub struct MutexGuard<'a, T> {
    inner: &'a Mutex<T>,
}
```

This is fine for cases where the `Mutex` is standalone. However, consider the common use pattern for a Mutex where it is put into an `Arc` to give the `Arc` a measure of safe interior mutability. Since an `Arc<T>`, when boiled down, can act as `&T`, one could create a pattern as follows:

```
pub struct MutexGuardArc<T> {
    inner: Arc<Mutex<T>>,
}

impl<T> Mutex<T> {
    pub fn lock_arc(this: &Arc<Self>) -> MutexGuardArc<T> {
        MutexGuardArc {
            inner: this.clone(),
        }
    }
}
```

The advantage of this is that this pattern elides the use of a lifetime which, for me personally, comes in handy when I'm using an `Arc<Mutex>` in cases where using lifetimes would unnecessarily complicate things. [`async_lock::Mutex`](https://docs.rs/async-lock/2.3.0/async_lock/struct.MutexGuardArc.html) provides this pattern already, and it would be nice if `lock_api` could provide that pattern as well.

I am willing to implement this myself if you approve of it.

**Comment by KOBA789** [comment]
I was looking for that too.

MutexGuardArc is not for just convinience, but make some locking technique possible.
For example, "latch crabbing" which is used in B-Tree traversaling is impossible without MutexGuardArc.
(I suppose so. let me know if it's possible)

Here is my implementation: https://github.com/KOBA789/qp/blob/9771276a3777b1bf27e02209eeccd4961d47ee18/src/lock.rs

**Comment by mystor** [comment]
For what it's worth, with `StableDeref` it's possible to abstract over arbitrary smart pointer types for the guard with a type like `OwnMutexGuard<Arc<Mutex<T>>>`, where the type `OwnMutexGuard<&'a Mutex<T>>` would be equivalent to `MutexGuard<'a, T>`. I threw together a quick & dirty implementation on top of `lock_api` in a gist: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8d9ad83701a1038aebae0cb08c455062

In addition to allowing cases like `Arc<Mutex<T>>`, this could be combined with crates like `owning_ref` to allow types like `OwnMutexGuard<OwningRef<Arc<MyStruct>, Mutex<T>>>` allowing locking a mutex within a more complex data structure while holding an owning reference.

I haven't put too much thought into what the interface might look like, and there may be some issues I'm not seeing off the top of my head, but perhaps allowing arbitrary smart pointer types within the mutex/rwlock guard could be a useful generalization here.

**Comment by JRAndreassen** [comment]
Hi...

I have this exact issue ...
Here is a excerpt of the relevant code
```rust
pub use std::{
    sync::{
        Arc,
    },
    collections::{HashMap},
    fmt,
};
pub use parking_lot::{
    RwLock,
    RwLockUpgradableReadGuard, 
    RwLockWriteGuard,
};

use serde::{
    Deserialize, Serialize,
};
pub use serde_json::{
    Result  as SerdeJsonResult, 
    Value   as SerdeJsonValue,
    Map     as SerdeJsonMap,
    json,
};

pub mod arc_rw{

    use super::*;
    pub type ArcRW<T> = Arc<RwLock<T>>;

    pub fn arcrw_new<T>(val:T) -> ArcRW<T>
    {
        Arc::new(RwLock::new(val))
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Credential {
    #[serde(rename = "Name", alias = "alias")]
    pub name: String,

    #[serde(rename = "SubSystem", alias = "subsystem")]
    pub subsystem: Option<String>,
}
impl Credential {

    pub fn new_arc() -> Arc<Self> {
        Arc::new(Self::default())
    }
    pub fn new_arcrw() -> CredentialArcRW {
        arc_rw::arcrw_new(Self::default())
    }

    //
    fn creds_blank() -> Credential {
        Credential {
            name: "default".to_owned(),
            subsystem: None,
        }
    }

    fn creds_default() -> Credential {
        Self::creds_blank()
    }

}
impl Default for Credential {
    fn default() -> Self {
        Self::creds_default()
    }
}

// ---------------------------------------
pub type CredentialArcRW = arc_rw::ArcRW<Credential>;


#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SecretsSection {
    pub instances: HashMap<String, CredentialArcRW>,

    #[serde(flatten)]
    extra: HashMap<String, SerdeJsonValue>,
}

impl SecretsSection {
    pub fn add_instances(&mut self, instances: &Vec<Credential>) -> usize {
        let mut retval: usize = 0;
        for curr in instances {
            if self.add_instance(curr.clone()) {
                retval += 1;
            }
        }
        retval
    }

    pub fn add_instance(&mut self, instance: Credential) -> bool {
        self.instances.insert(
            instance.name.to_owned().to_lowercase(), 
            arc_rw::arcrw_new(instance))
          .is_none()
    }
}

fn main() {
    
    println!("Hello, world!");
}
```
Which yields the following errors
```rust
  Compiling testarcrw v0.1.0 (C:\Development\Rust\test\testarcrw)
error[E0277]: the trait bound `std::sync::Arc<lock_api::rwlock::RwLock<RawRwLock, Credential>>: Deserialize<'_>` is not satisfied
  --> src\main.rs:77:5
   |
77 |     pub instances: HashMap<String, CredentialArcRW>,
   |     ^^^ the trait `Deserialize<'_>` is not implemented for `std::sync::Arc<lock_api::rwlock::RwLock<RawRwLock, Credential>>`
   |
   = note: required because of the requirements on the impl of `Deserialize<'_>` for `HashMap<std::string::String, std::sync::Arc<lock_api::rwlock::RwLock<RawRwLock, Credential>>>`
   = note: required by `next_value`

error[E0277]: the trait bound `std::sync::Arc<lock_api::rwlock::RwLock<RawRwLock, Credential>>: Serialize` is not satisfied
  --> src\main.rs:77:5
   |
77 |     pub instances: HashMap<String, CredentialArcRW>,
   |     ^^^ the trait `Serialize` is not implemented for `std::sync::Arc<lock_api::rwlock::RwLock<RawRwLock, Credential>>`
   |
   = note: required because of the requirements on the impl of `Serialize` for `HashMap<std::string::String, std::sync::Arc<lock_api::rwlock::RwLock<RawRwLock, Credential>>>`
   = note: required by `serialize_entry`
```

Any thoughts or insight would be appreciated...
  Thanks
  JR
P.S. the nightly option compiles, but do not have the option of using nightly

**Comment by gmorenz** [comment]
I tried spending some time figuring out the owningRef version (except for `Mutex` instead of `RwLock`), failed, decided that it apparently needs unsafe anyways (judging by the code linked previously), and just went with the code below.

I second that it would be very nice to have arc based muted guards in the crate. I don't think users (like me) re-inventing the wheel on how to do this is a good idea. 

Implemented properly is the idea of `Arc` based guards, or `StableDeref` based guards, something that would potentially be merged?

```rust
/// Arc<Mutex> Guard, with 'static lifetime

pub struct ArcGuard<T> {
    mutex: Arc<Mutex<T>>,
}

impl<T> ArcGuard<T> {
    pub fn lock(mutex: Arc<Mutex<T>>) -> Self {
        use parking_lot::lock_api::RawMutex;
        unsafe{ mutex.raw().lock() };
        ArcGuard {
            mutex
        }
    }
}

impl<T> std::ops::Deref for ArcGuard<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        unsafe{ &*self.mutex.data_ptr() }
    }
}

impl<T> std::ops::DerefMut for ArcGuard<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe{ &mut *self.mutex.data_ptr() }
    }
}

impl<T> Drop for ArcGuard<T> {
    fn drop(&mut self) {
        use parking_lot::lock_api::RawMutex;
        unsafe{ self.mutex.raw().unlock() }
    }
}
```

**Comment by Amanieu** [comment]
I'm generally in favor of the idea! It would be nice for `ArcMutexGuard` to support all the same features as a normal `MutexGuard`. I'm happy to accept a PR for this.

**Comment by Byron** [comment]
With this resolved and the `arc_lock` feature available in `master`, is there a plan to cut a release with this?

For `gitoxide` I am trying to [abstract away references](https://github.com/Byron/gitoxide/blob/d793ecd00f55b5bf7c6dcaee8772975e97bd5e30/git-repository/src/easy.rs#L28-L31) to let them be backed by [`Rc<RefCell>` or `Arc<RwLock>`](https://github.com/Byron/gitoxide/blob/d793ecd00f55b5bf7c6dcaee8772975e97bd5e30/git-repository/src/easy.rs#L236-L249) (_even though RefCells probably require GATs to be available_). `Arc<RwLock>` along with `arc_lock` was a god-sent as it doesn't require lifetime specifications.
