### ISSUE TITLE
Lockup when using fair unlocks.

### ISSUE THREAD

**Issue by sstewartgallus** [Amanieu/parking_lot#29]
I was benchmarking parking lot against my own [crate](https://sstewartgallus.com/git?p=uevents-rs.git;a=summary) and found a lock up bug  https://github.com/sstewartgallus/parkinglotbug

The benchmark uses parking lot to implement an event semaphore and then uses the event semaphore to implement a lock.

Run cargo bench to get a lockup.

My platform is a 2 core x86-64 Linux machine.

**Comment by Amanieu** [comment]
I'm getting a segfault instead of a lockup on that test.

**Comment by Amanieu** [comment]
OK, I've fixed the segfault and can see the lockup now.

**Comment by Amanieu** [comment]
Sorry that this took a while, I've been busy lately. It should be fixed now.

**Comment by sstewartgallus** [comment]
Thank you.
