### ISSUE TITLE
Add is_locked_exclusive to RwLock

### ISSUE THREAD

**Issue by topecongiro** [Amanieu/parking_lot#293]
It would be great if you could add `is_locked_exclusive` (or whatever the name is) to `RwLock` API. The method shall return `true` if the lock is held exclusively and `false` otherwise, ideally without modifying the underlying lock data structure.

The method will be useful when constructing certain algorithms (e.g., optimistic latching). Currently, `parking_lot` only exposes `is_locked` which returns true against both shared/exclusive, or `try_write` which will modify the lock data structure.

**Comment by declanvk** [comment]
This should have been closed by #303 , @topecongiro could you check out the PR and see if it works for you?

**Comment by topecongiro** [comment]
@declanvk Thank you for the PR, and sorry for the late reply.

Regarding implementing HybridLocking in the paper, I think that we need to use `Ordering::Acquire` in `is_locked` and `is_locked_exclusive`, or otherwise, there is a chance that the instruction reading the version gets reordered before `is_locked_exclusive`.
