### ISSUE TITLE
CI is running an extremely old version of Rust

### ISSUE THREAD

**Issue by Vurich** [Amanieu/parking_lot#295]
While working on https://github.com/Amanieu/parking_lot/pull/290, I fixed a deprecation warning (`std::sync::atomic::spin_loop_hint` is now `std::hint::spin_loop`). However, this caused errors on CI because it is running Rust 1.41, whereas the latest stable version is 1.54. This might be intentional, as `parking_lot` is a reasonably fundamental crate in the Rust ecosystem and so should support older versions, but 1.41 is now over a year and a half old, `std::hint::spin_loop` has been stable for almost a year and `spin_loop_hint` has been deprecated for almost as long as that.

**Comment by Amanieu** [comment]
I'm planning to do a major version bump of parking_lot soon, so it's fine to introduce breaking changes. In the meantime just upgrade the minimum Rust version in CI to the latest stable.
