### ISSUE TITLE
Would a new release be possible to get the `arc_lock` feature to crates.io?

### ISSUE THREAD

**Issue by Byron** [Amanieu/parking_lot#296]
Thanks for creating `parking_lot` as the crate not only allows me to rest assured it's the fastest locks around, but even more importantly has an API…without poison 🤦‍♂️😅.

For implementing the `Easy` mode in the `git-repository` crate of the [`gitoxide`](https://github.com/Byron/gitoxide) project I was in dire need of the unreleased `arc_lock` feature in order to generalize over [shared](https://github.com/Byron/gitoxide/blob/5375fc872b9af2526683326f58e9c3d7f20ef166/git-repository/src/easy/impls.rs#L58-L73) and [exclusive](https://github.com/Byron/gitoxide/blob/5375fc872b9af2526683326f58e9c3d7f20ef166/git-repository/src/easy/impls.rs#L108-L122) references to a git repository. 

Using the `Arc<RwLock>` extensions allows me to work around the absence of GATs, which would solve the issue for good.

For an intermediate release (even an RC or alpha) I would be most grateful as I could bring the abstractions back that are meant for the server side.

Thanks a lot for your consideration.

**Comment by Amanieu** [comment]
Done!
