### ISSUE TITLE
parking_lot_core increasing MSRV in a "sever-compatible" version broke downstream builds

### ISSUE THREAD

**Issue by robjtede** [Amanieu/parking_lot#297]
`parking_lot_core` v0.8.4 increased it's MSRV to 1.49 in which `hint::spin_loop()` is used, a previously unstable feature.

Now, in a fresh "hello world" Actix Web v3 application (where the MSRV of Actix Web v3 is 1.46) this compiler error occurs.

```
error[E0658]: use of unstable library feature 'renamed_spin_loop'
  --> /Users/rob/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.8.4/src/spinwait.rs:16:9
   |
16 |         hint::spin_loop()
   |         ^^^^^^^^^^^^^^^
   |
   = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information
```

In general, an MSRV change should occur in conjunction with a semver bump so that `cargo update` does not break existing applications. I.e., this release of `parking_lot_core` should have been v0.9.0.

In my opinion, this release should be yanked and re-released with a more appropriate version number.

**Comment by bjorn3** [comment]
A lot of crates bump their MSRV with semver compatible releases, only a couple guarantee that they will only with a semver incompatible release. I believe there is an unstable cargo feature to indicate MSRV to make this nicer for users in the future.

**Comment by robjtede** [comment]
From the parking_lot readme:

> The current minimum required Rust version is 1.36. Any change to this is considered a breaking change and will require a major version bump.

Ignoring the outdated version, this crates own policy is that a "major" bump is required to change it.

**Comment by Amanieu** [comment]
Done
