### ISSUE TITLE
Why not spin wait inside the parking_lot park?

### ISSUE THREAD

**Issue by sstewartgallus** [Amanieu/parking_lot#30]
You spin a bit in https://github.com/Amanieu/parking_lot/blob/master/src/raw_mutex.rs#L149 .

Why not spin a bit in https://github.com/Amanieu/parking_lot/blob/master/core/src/thread_parker/linux.rs#L49 ?

Maybe I'm missing something but spinning in the parking_lot park should be more efficient than spinning on the address directly because each thread has its own local data that it would spin on.

I benchmarked it and a straightforward attempt seemed to make mutexes slightly faster.

**Comment by Amanieu** [comment]
The problem is that to reach `park()` you need to register the current thread in a global hash table, which involves a taking a few internal locks. By spinning in the mutex, you avoid all this since no thread registration is needed.
