### ISSUE TITLE
lock_api: const INIT instead of new() in RawMutex

### ISSUE THREAD

**Issue by StephanvanSchaik** [Amanieu/parking_lot#301]
Hi,

For a project I am working in no_std, I would like to use the lock_api crate to help with the implementation of `Mutex` and other synchronization primitives. The platform I am working on already has an API for mutual exclusion in C that I would just like to wrap. However, there is one problem with the `RawMutex` trait, and that is that it expects a `const INIT`, while I need to call a function to initialize my mutex.

Would it be possible to extend the `RawMutex` trait, and possibly others, with `fn new() -> Self;` such that we can actually initialize the mutex on platforms where this is necessary? In theory, it could default to return `Self::INIT`, but that would require `Self` implementing `Sized` as follows:

```rust
pub unsafe trait RawMutex: Sized {
    const INIT: Self;

    fn new() -> Self {
        Self::INIT
    }
}
```

or:

```rust
pub unsafe trait RawMutex {
    const INIT: Self;

    fn new() -> Self where Self: Sized {
        Self::INIT
    }
}
```

**Comment by bjorn3** [comment]
Based on the documentation it seems that using a mutex object is incorrect anyway as they can be recursively locked, which would give multiple mutable references to the same memory. This is UB. Also I suspect that mutex objects can't be moved, which means that if you want to use them you have to box them like libstd does for userspace windows and pthread (unix) mutexes.

Maybe it makes more sense to avoid lock-api entirely and write the entire `Mutex` implementation directly yourself?

**Comment by dwattttt** [comment]
> The problem with adding `fn new` is that it prevents `Mutex::new` from being a `const fn` in the future once `const fn` trait bounds are stable.
> 
> Could you select an initial value for `INIT` such that you can automatically initialize the platform mutex on first use?

Ironically, wouldn't this initialization itself need to be locked? If multiple threads attempted to lock at the same time, the implicit initialization would occur multiple times, with unpredictable results.
