### ISSUE TITLE
Selectable synchronization primitives

### ISSUE THREAD

**Issue by reem** [Amanieu/parking_lot#31]
Forgive me if this is just totally outside the scope of this crate, given that I'm not really sure what level of added complexity/overhead this feature would add, but it would be wonderful to be able to do a "select" operation on multiple synchronization primitives (or even just multiple of the same kind).

Currently when using the `std::sync`/pthread primitives whenever I run into a case where I just want to select on e.g. a condition variable and a mutex or two condition variables I have to stop and go back to the whiteboard and figure out another strategy. Being able to select would open up a large number of other strategies and make implementing all sorts of things easier.

**Comment by Amanieu** [comment]
Unfortunately, the parking lot only allows a thread to wait in a single queue at once, which means that this isn't possible with the current system.

**Comment by reem** [comment]
Could the parking lot be reasonably adapted to allow threads to wait in multiple queues, or would this require a total redesign of the system? I'm curious how much more fundamentally complicated this would be vs. the existing capabilities of the system.

**Comment by Amanieu** [comment]
I don't think this is possible without significant changes to the system, unfortunately.

You might be better off using futures in your case since they allow waiting for multiple futures at once.
