### ISSUE TITLE
nightly feature fails to compile

### ISSUE THREAD

**Issue by quininer** [Amanieu/parking_lot#312]
`llvm_asm!` was removed in the latest nightly, which caused the latest version (0.11.2) of `parking_lot` on crates.io to fail to compile with the `nightly` feature enabled.

`parking_lot` on master seems to [have switched to `asm!`](https://github.com/Amanieu/parking_lot/pull/304), maybe we can release a new version?

**Comment by superwhiskers** [comment]
i second this. i've had to switch to including `parking_lot` via git for it to build. i think a new release would be the best way to fix this problem

**Comment by Amanieu** [comment]
I published a new release.
