### ISSUE TITLE
Please consider using feature flags instead of conditional platform configurations

### ISSUE THREAD

**Issue by c410-f3r** [Amanieu/parking_lot#320]
https://github.com/Amanieu/parking_lot/blob/847b5cab64fe3a87f853de0cac479d78e5a7ee77/core/Cargo.toml#L19-L31

They bloat `Cargo.lock`, waste network resources and make compile times take longer. In the end everything is simply thrown away if the platform does not match the host or the binary target.

![Capture d’écran de 2022-02-17 08-34-06](https://user-images.githubusercontent.com/17877264/154473249-5b5fd7b7-d952-43a4-8baa-e76bd4ae510e.png)

I know such request is a maintenance burden and you might be thinking that Cargo should handle this stuff properly. Well, in any case it doesn't hurt ask :)

**Comment by CryZe** [comment]
>  fetch them remotely and make compile times take longer just to throw them away if the platform does not match the host or the binary target

Cargo does not fetch any crates that aren't included for the target platform.

**Comment by c410-f3r** [comment]
> > fetch them remotely and make compile times take longer just to throw them away if the platform does not match the host or the binary target
> 
> Cargo does not fetch any crates that aren't included for the target platform. Just because they are included in the Cargo.lock doesn't mean they are ever fetched.

Really? Hum... I could swear they were downloaded. 

Do you know any Cargo issue or PR that corroborates this feature?

**Comment by CryZe** [comment]
You can check any of the CI logs here for example: https://github.com/Amanieu/parking_lot/runs/5083867926?check_suite_focus=true#step:4:18

There's no download or build of any Windows packages in this Ubuntu build.

And the Windows build only downloads the one relevant for the specific architecture: https://github.com/Amanieu/parking_lot/runs/5083868420?check_suite_focus=true#step:4:13

**Comment by c410-f3r** [comment]
Hehehe... You are right

![Capture d’écran de 2022-02-17 09-35-54](https://user-images.githubusercontent.com/17877264/154483340-7ba9061b-0b8c-4adb-b66e-d637e9479479.png)


Also worth mentioning https://github.com/rust-lang/cargo/issues/5896#issuecomment-414369032

Thanks @CryZe for the clarification! Let me close this issue
