### ISSUE TITLE
Condvar::wait_while and Condvar::wait_timeout_while convenience methods

### ISSUE THREAD

**Issue by bryanhitc** [Amanieu/parking_lot#329]
The standard library has  `Convar::wait_while` and `Convar::wait_timeout_while` methods that take a `condition: impl Fn(&mut T) -> bool`. These convenience methods are great since the following pattern is relatively common:

```rs
while condition(&mut *lock_guard) {
  cv.wait(lock_guard);
}

// condition is now false
```

I think it'd be great to have these convenience methods built-in, but I can also see an argument being made for not wanting to clutter the public API. Thoughts?

I'm more than happy to submit the PR if this functionality is desired.

**Comment by Amanieu** [comment]
Sure! I'd be happy to accept a PR for this.
