### ISSUE TITLE
Does not compile on latest nightly rust

### ISSUE THREAD

**Issue by riley-martin** [Amanieu/parking_lot#345]
When I try to compile parking_lot with the latest nightly rustc, it gives me an error about not finding any macro named `llvm_asm!`. It seems that since `nightly-2022-01-17` rustc has removed support for `llvm_asm!` in favor of the new `asm!` macro.

**Comment by faern** [comment]
This was fixed in #304. Try updating `parking_lot`?

**Comment by riley-martin** [comment]
Oops, you are right. I wasn't aware that I was using an outdated version. I'll close the issue.
