### ISSUE TITLE
Why are these types not in the standard library?

### ISSUE THREAD

**Issue by torkleyy** [Amanieu/parking_lot#36]
I'm asking myself, if these are faster why aren't they in `libstd`? I think read something about platform limitations, but it's not really clear why the standard library has to use platform-specific types. I also saw other people wondering about this, might be worth adding it to the README.

**Comment by Amanieu** [comment]
See rust-lang/rfcs#1632.

**Comment by torkleyy** [comment]
Great, thanks! I think I'll be using this crate only then. :+1:

**Comment by Techcable** [comment]
@alexcrichton mentioned getting this in the nursery. Is that a possibility?

**Comment by tbu-** [comment]
In https://github.com/rust-lang/rust/issues/53127#issuecomment-417032962 it is mentioned that Rust might be more likely to accept parking_lot into the standard library ([even rustc uses parking_lot](https://github.com/rust-lang/rust/blob/b8d45da2747c0b0943f48854e653ebe0d1ba60c9/src/librustc/Cargo.toml#L32)).

It's probably needed to write another RFC to make that change though. I don't think I have the necessary expertise to write it. If someone were interested in this and had some time, it would be nice if they could write it. :)

One more possible concern that didn't get mentioned in the original RFC thread would be whether the code size of parking_lot is bigger than the one of the synchronization primitives in libstd.
