### ISSUE TITLE
Comparing two Mutex contents

### ISSUE THREAD

**Issue by enricozb** [Amanieu/parking_lot#365]
I'm attempting to compare the contents of two `Mutex`es, but I'm unable to because of the signature of `MutexGuard::map`, specifically because it requires that the provided function returns a `&mut U` (and I understand that this is generally necessary for common uses of `MutexGuard::map`. Here's my current attempt:

```rust
use parking_lot::Mutex;
use parking_lot::lock_api::MutexGuard;

pub struct State<T> {
  inner: Mutex<T>,
}

impl<T: PartialEq<Rhs>, Rhs> PartialEq<State<Rhs>> for State<T> {
  fn eq(&self, other: &State<Rhs>) -> bool {
    **MutexGuard::map(self.inner.lock(), move |inner| {
      &mut MutexGuard::map(other.inner.lock(), |other| inner == other)
    })
  }
}
```
But this gets a compiler error:
```
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
  --> src/lib.rs:11:56
   |
11 |       &mut MutexGuard::map(other.inner.lock(), |other| inner == other)
   |                                                        ^^^^^^^^^^^^^^
   |                                                        |
   |                                                        expected `&mut _`, found `bool`
   |                                                        help: consider mutably borrowing here: `&mut (inner == other)`
   |
   = note: expected mutable reference `&mut _`
                           found type `bool`
```

And I can't just mutably borrow there since that would be returning a reference to a temporary value.

I understand that this would cause a deadlock if a Mutex is compared with itself.

Any suggestions?

**Comment by bjorn3** [comment]
You can write it as

```rust
let inner = self.inner.lock();
let other = other.inner.lock();
inner == other
```

right? `map` is meant to be used when you want to get a subfield of a locked value. For example `MutexGuard::map(a.lock(), |a| &mut a.some_field)` to make the mutex guard point to `a.some_field` rather than the whole `a`.

**Comment by enricozb** [comment]
Lol can't believe I couldn't figure this out, you have to dereference them:
```
use parking_lot::Mutex;
use parking_lot::lock_api::MutexGuard;

pub struct State<T> {
  inner: Mutex<T>,
}

impl<T: PartialEq<Rhs>, Rhs> PartialEq<State<Rhs>> for State<T> {
  fn eq(&self, other: &State<Rhs>) -> bool {
    *self.inner.lock() == *other.inner.lock()
  }
}
```
