### ISSUE TITLE
Replace thread_id crate with std std::thread::Thread::id

### ISSUE THREAD

**Issue by frewsxcv** [Amanieu/parking_lot#38]
https://doc.rust-lang.org/nightly/std/thread/struct.Thread.html#method.id

`ThreadId` is now available in the standard library

**Comment by Amanieu** [comment]
Unfortunately, I require the thread ID as a `usize` so that I can put the value inside an `AtomicUsize`. The standard library `ThreadId` type is an opaque value that can't be converted to an integer.
