### ISSUE TITLE
Ticketed lock implementation?

### ISSUE THREAD

**Issue by mathstuf** [Amanieu/parking_lot#40]
It'd be nice to have a ticketed lock (similar to [this crate](https://github.com/kvark/ticketed_lock)) using parking lot. Or should ticketed_lock be rebased/forked to be on top of parking lot instead?

**Comment by Amanieu** [comment]
You can build a custom lock implementation on top of `parking_lot_core`. It doesn't need to be part of the `parking_lot` crate.

**Comment by mathstuf** [comment]
Would it make sense? Or is it different enough to be better as a separate crate?

**Comment by Amanieu** [comment]
I think that it would be better off as a separate crate.

**Comment by mathstuf** [comment]
Thanks.
