### ISSUE TITLE
Why does `notify_one_slow` return true even if threads were only requeued, and not unparked?

### ISSUE THREAD

**Issue by bzm3r** [Amanieu/parking_lot#401]
This is a conceptual question. 

In `notify_one_slow` on `Condvar`, we have:

https://github.com/Amanieu/parking_lot/blob/4adcfdda3cfb4e70cfd876ccbeeb176cb2b88c5b/src/condvar.rs#L174

Suppose `res.unparked_threads == 0`, but `res.requeued_threads > 0`, then should `notify_one_slow` return true?

**Comment by Amanieu** [comment]
`notify_one` returns true if a thread was waiting on the condvar and has now been woken up. It doesn't matter whether this was done by waking it up directly or requeuing it to the mutex so that it will be woken up when the mutex is unlocked.

**Comment by bzm3r** [comment]
@Amanieu Thank you, that makes sense!
