### ISSUE TITLE
Use std::sync::atomic::hint_core_should_pause in SpinWait

### ISSUE THREAD

**Issue by jonhoo** [Amanieu/parking_lot#43]
Now that Rust (nightly) has [`std::sync::atomic::hint_core_should_pause`](https://doc.rust-lang.org/nightly/std/sync/atomic/fn.hint_core_should_pause.html), `parking_lot_core::SpinWait` should probably use that function directly instead of using `asm!("" ::: "memory" : "volatile")` in `cpu_relax`. Probably won't make a difference in terms of performance (I assume they basically do the same thing), but may ease portability.

**Comment by Amanieu** [comment]
I really like this, however I would like to at least wait until it is stabilized before using it.

**Comment by jonhoo** [comment]
Tracked in https://github.com/rust-lang/rust/issues/41196

**Comment by stjepang** [comment]
I have a concern with the current implementation of `Spinwait::spin`:

```rust
#[inline]
pub fn spin(&mut self) -> bool {
    if self.counter >= 20 {
        return false;
    }
    self.counter += 1;
    if self.counter <= 10 {
        cpu_relax(4 << self.counter);
    } else {
        thread_yield();
    }
    true
}
```

The pause instruction will be executed 8184 times before calling `thread_yield()`.

However, take a look at to [Intel's manual](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-optimization-manual.pdf) (section 8.4.7 Pause Latency in Skylake Microarchitecture):

> Such short wait loops tend to last between tens and a few hundreds of cycles, so performance-wise it is more beneficial to wait while occupying the CPU than yielding to the OS. When the wait loop is expected to last for thousands of cycles or more, it is preferable to yield to the operating system...

> The latency of PAUSE instruction in prior generation microarchitecture is about 10 cycles, whereas on Skylake microarchitecture it has been extended to as many as 140 cycles. 

This indicates that executing the instruction 8184 times is way too many. Since one instruction takes 10-140 cycles, and yielding to the OS should happen after several thousands of cycles, then perhaps a better number would be between 10 and 100?

Perhaps the following would be a more reasonable implementation that doesn't burn CPU time as much:

```rust
#[inline]
pub fn spin(&mut self) -> bool {
    if self.counter >= 120 {
        return false;
    }
    self.counter += 1;
    if self.counter <= 100 {
        cpu_relax(1);
    } else {
        thread_yield();
    }
    true
}
```

**Comment by Amanieu** [comment]
I want to keep the exponential backoff since it helps improve throughput. How about simply reducing the counter thresholds:

```rust
#[inline]
pub fn spin(&mut self) -> bool {
    if self.counter >= 10 {
        return false;
    }
    self.counter += 1;
    if self.counter <= 6 {
        cpu_relax(1 << self.counter);
    } else {
        thread_yield();
    }
    true
}
```

This will call the pause instruction 127 times, after which it will try yielding to the OS 3 times, before finally just blocking on a futex.

**Comment by stjepang** [comment]
To be precise, it's [126 pauses and 4 yields](https://play.rust-lang.org/?gist=896de8e075b9eab892d7229390f09b9d&version=stable). :) But sounds good to me!

**Comment by cesarb** [comment]
Related to @stjepang 's comments, a performance issue in dotnet on Skylake processors has been traced to a similar loop:

- https://aloiskraus.wordpress.com/2018/06/16/why-skylakex-cpus-are-sometimes-50-slower-how-intel-has-broken-existing-code/
- https://github.com/dotnet/coreclr/issues/13388
- https://news.ycombinator.com/item?id=17336853

The pause instruction sleeps 14x longer on Skylake, so these loops will take 14x longer.

**Comment by amaranth** [comment]
FYI, this was put into use in bf0fa8680fc so this should probably be closed. Any discussion about the number of times it should be called (which doesn't appear to have changed) would perhaps make sense as a separate issue.

**Comment by Amanieu** [comment]
The code currently uses `spin_loop_hint`, so this issue can be closed.
