### ISSUE TITLE
New `parking_lot` release?

### ISSUE THREAD

**Issue by Palkovsky** [Amanieu/parking_lot#439]
Hello,

Latest `parking_lot` release (`0.12.1`) depends on old `windows-targets 0.48.5`, which blocks us from linking our Windows x64 application onto the new ARM64EC target (` arm64ec-pc-windows-msvc`). Current `master` uses `windows-targets 0.52` which is fine for ARM64EC, but we cannot patch our project directly, since `parking_lot` is a transitive dependency for us. 

Is a new release planned in the near future? That would make our life much easier.

**Comment by Amanieu** [comment]
I just published a new release.

**Comment by Palkovsky** [comment]
Thank you. That solved our issue.
