### ISSUE TITLE
Why do guard locks without `send_guard` not explicitly implement `!Send`?

### ISSUE THREAD

**Issue by Fishrock123** [Amanieu/parking_lot#446]
I am wondering why this crate chooses to have `GuardNoSend` use an empty raw pointer (`*mut ()`) internally to mark that compiler can't implement `Send` on it rather than have `GuardNoSend` explicitly implement `!Send`, like how [the std library does it for `MutexGuard`](https://github.com/rust-lang/rust/blob/bcf1f6db4594ae6132378b179a30cdb3599a863d/library/std/src/sync/mutex.rs#L214-L215)?

I feel like it would be much clearer in rust doc if `parking_lot` would explicitly have `!Send` for it's non-sendable guards.

is there some reason I am missing for why this crate does it in this way?

**Comment by bjorn3** [comment]
`impl !Send for T {}` is unstable.

**Comment by Fishrock123** [comment]
Right, negative trait bounds, forgot that wasn't special to `!Send`. Hopefully some day.
