### ISSUE TITLE
SIGSEGV when it tries to wait for a futex

### ISSUE THREAD

**Issue by techmetx11** [Amanieu/parking_lot#451]
The code segfaults when it tries to wait for a futex (related to Tokio)
More info: https://github.com/iv-org/inv_sig_helper/issues/12
A coredump of the crash and build is provided at https://github.com/iv-org/inv_sig_helper/issues/12#issuecomment-2289084639
From the coredump, the program is shown crashing at these first few locations in the code:
1. unknown function (0x00007fc5ed1a3719)
2. https://github.com/Amanieu/parking_lot/blob/master/core/src/thread_parker/linux.rs#L112
3. https://github.com/Amanieu/parking_lot/blob/master/core/src/thread_parker/linux.rs#L66
4. https://github.com/Amanieu/parking_lot/blob/master/core/src/parking_lot.rs#L635
5. https://github.com/Amanieu/parking_lot/blob/master/core/src/parking_lot.rs#L600

**Comment by Amanieu** [comment]
Are you sure it's actually crashing in that thread? It seems like this is just the main thread which is blocked waiting on a lock while the crash is happening in another thread.

**Comment by techmetx11** [comment]
All the other threads are also blocked waiting for a lock (in the coredump)

**Comment by Amanieu** [comment]
All of the threads in that core dump are in system calls, which shouldn't be able to cause a SIGSEGV. It seems the core dump was not taken at the moment the crash happened.

**Comment by techmetx11** [comment]
> All of the threads in that core dump are in system calls, which shouldn't be able to cause a SIGSEGV. It seems the core dump was not taken at the moment the crash happened.

That's weird, because the kernel makes a core dump after the program crashed

Also, it seems like it causes a malloc header corruption at times, as seen in the linked issue
