### ISSUE TITLE
Extract out useful sub-crates.

### ISSUE THREAD

**Issue by jonhoo** [Amanieu/parking_lot#5]
parking_lot contains a number of useful pieces that are relatively independent. The implementation of `SpinWait` for example could come in handy for a number of other projects. Any chance of these being split out into independent crates that are then used by parking_lot?

**Comment by Ericson2314** [comment]
I haven't looked around, buts its possible that some things could go in https://github.com/mvdnes/spin-rs if they only rely on core. For one, that library doesn't do any exponential backoff while `SpinWait` does.

**Comment by jonhoo** [comment]
Seems reasonable. It'd also be good to expose `SpinWait` directly, as it can be useful without the locking mechanism too (e.g., if you're implementing your own synchronization primitives).

**Comment by jonhoo** [comment]
Ping @mvdnes to see if that'd be a tractable option.

**Comment by Amanieu** [comment]
The problem is that `SpinWait` will fall back to OS-based thread yielding, which isn't available in a `no_std` context.

**Comment by jonhoo** [comment]
Could the yield fallback be placed under a `#cfg` for the `no_std` case?

**Comment by Amanieu** [comment]
I guess you could do that. In any case, this issue should probably be moved to spin-rs, unless there is some other part of the code that you think would be useful to split off into a separate crate.

**Comment by jonhoo** [comment]
Hmm, lock elision and thread parker maybe, though both of those are less clear. I'll file a request over in the spin-rs repo and link back here.

**Comment by Ericson2314** [comment]
Isn't elision be a good candidate for `spin` too?

**Comment by Amanieu** [comment]
`SpinWait ` is now available in `parking_lot_core`.
