### ISSUE TITLE
Document features

### ISSUE THREAD

**Issue by sanmai-NL** [Amanieu/parking_lot#54]
The `deadlock_detection` feature is documented a bit indirectly via API docs of the core crate. The `nightly` feature is only discussed on the issue tracker.

If this summary correct, could you please document all features in the `README` and/or API docs, in a more conspicuous way?

**Comment by Amanieu** [comment]
The `deadlock_detection` feature is mentioned in the feature list in the `README`. The `README` also shows how to use  the `nightly` feature to enable nightly-only functionality.

**Comment by sanmai-NL** [comment]
The confusion is, `nightly` is mentioned but not explained in the `README`. In the `README`, there’s a section ‘Nightly vs stable’, but it isn’t clear to me what the relation between the ‘nightly’ feature and using a nightly compiler is. I have been using the crate in the `nightly` channel without the `nightly` feature so far.

**Comment by sanmai-NL** [comment]
As for `deadlock_detection`, for some reason I did not spot it in the `README`. It would be ideal if the features are listed under a heading somewhere in addition to or in place of being mentioned in prose/lists.

**Comment by Amanieu** [comment]
Should be better now.
