### ISSUE TITLE
NT Keyed Events-Panic

### ISSUE THREAD

**Issue by heliasi4** [Amanieu/parking_lot#59]
Hey, I get:
_panicked at 'parking_lot requires either NT Keyed Events (WinXP+) or WaitOnAddress/WakeByAddress (Win8+)'_ 
when using a library that depends on parking_lot's Mutex etc.

What exactly does this mean? Do I have to install something in particular?
Running Windows 7, 64bits.

**Comment by Amanieu** [comment]
I just published a new version of the `parking_lot_core` crate which should hopefully fix this. Can you try again and let know if there are any issues?
