### ISSUE TITLE
Consider bumping the minor version on rustc bumps

### ISSUE THREAD

**Issue by torkleyy** [Amanieu/parking_lot#61]
[This PR](https://github.com/Amanieu/parking_lot/pull/39) bumped the required Rust version from 1.13 to 1.18. While I don't think that's a problem since many users have that version already, I think it's a good practice to bump the minor version instead of the patch version on such a release. Releasing just a patch version can break other Travis builds that assure a certain rustc version works.

**Comment by CryZe** [comment]
Below 1.0, the minor version is considered a breaking change by cargo. However increasing the minimum rust compiler version is not considered a breaking change by the rust community, so it's "okay" to bump the minor version here. However ideally this would've been coupled with a full on switch to 0.6.

**Comment by torkleyy** [comment]
It's just my personal preference, so that builds don't break. Unfortunately, cargo can not handle Rust version bumps :(
