### ISSUE TITLE
0.5.5 forces all packages upgrade rust to 1.24

### ISSUE THREAD

**Issue by fafhrd91** [Amanieu/parking_lot#71]
i am not directly depend on parking_lot, but latest minor release forces me to upgrade rust to 1.24
because of `spin_loop_hint`

i consider this change as major breaking change

**Comment by fafhrd91** [comment]
you can close ticket if you think this is ok

**Comment by Amanieu** [comment]
I'm going to close this for now, any discussion should go to one of the links I posted above.

IMO, Cargo really should just add a field in Cargo.toml to specify the minimum required Rust version. Dependency resolution would then take this into account to find the release with the highest version that supports the current Rust version.

**Comment by fafhrd91** [comment]
what is annoying in this situation, I don't use parking_lot in my code and still forced to upgrade rust by it.

but I guess that is fine

**Comment by matklad** [comment]
>I don't use parking_lot in my code and still forced to upgrade rust by it.

Note that you are not *strictly* forced to upgrade rust. For a binary application with a lockfile, you can run `cargo generate-lockfile && cargo update --package parking_lot --precise 0.5.4`, and that should work with older Rust. For a libirary, your consumers would have to do that upgrade. 

This is of course a horrible workaround, and indeed should be fixed on the Cargo side.
