### ISSUE TITLE
Consider making "fairness" something decided when a lock is created

### ISSUE THREAD

**Issue by mehcode** [Amanieu/parking_lot#76]
Currently we have `MutexGuard::unlock_fair()`. It'd be quite convenient for me to instead have something like that:

```rust
let lock = Mutex::new_fair(()); 
let lock = Mutex::new((), /* fair: */ false);  // or
```

Which would allow the normal `Drop` to be fair or unfair.

**Comment by paulocsanz** [comment]
Would #204 solve this for you?

**Comment by mehcode** [comment]
That looks awesome. Thanks for implementing it.
