### ISSUE TITLE
implement Clone for RwLockReadGuard

### ISSUE THREAD

**Issue by CodesInChaos** [Amanieu/parking_lot#78]
Currently `RwLock::read_recursive()` can be used to achieve the same effect, but `clone` is easier to use and doesn't require a reference to the underlying lock.

**Comment by Amanieu** [comment]
I've added this in lock_api v0.1.2, which parking_lot uses.

**Comment by CodesInChaos** [comment]
One thing I'm not sure about: Is this technically a breaking change because `guard.clone()` used to clone the target and now clones the guard?

**Comment by Amanieu** [comment]
You're right, it was indeed a breaking change. I added a test and yanked the version with clone.

**Comment by CodesInChaos** [comment]
I think for now the best workaround is a static `RwLockReadGuard::clone(guard:&Self)` method, which has the nice property that it shouldn't break if it's later turned into an instance method.

But I'm still in favour of implementing `Clone`, following the precedent set by other smart-pointers like `Arc`, the next time you introduce other breaking changes.
