### ISSUE TITLE
Expose raw locking primitives

### ISSUE THREAD

**Issue by kvark** [Amanieu/parking_lot#84]
Types like `ParkingLotRwLock` are needed for the outside world in order to build any type safe primitives using `lock_api` generic interface. Any reason they are not public?

**Comment by Amanieu** [comment]
What are you trying to do with the raw locks? You should have everything that you need with the normal `Mutex` and `RwLock` types. You can do anything that the raw API can with `Mutex<()>` and `Mutex::force_unlock`.

The `lock_api` is primarily intended for people implementing different lock types that are not based on parking_lot, such as spinlocks and using Linux futexes directly.

**Comment by kvark** [comment]
I'm trying to implement my own concurrent map (https://pastebin.mozilla.org/9089970) that is generic across `lock_api` traits. In order to actually use it, or even just test it, I need to have an implementation of `RawRwLock`, of which I only know `parking_lot`'s one. Obviously, using `Mutex<()>` will no longer be generic across raw lock implementations.

**Comment by Amanieu** [comment]
Added `RawMutex` and `RawRwLock` in 0.6.3.

**Comment by kvark** [comment]
Thank you!
