### ISSUE TITLE
"this is an associated function, not a method" error with RwLockUpgradableReadGuard::upgrade 

### ISSUE THREAD

**Issue by Valloric** [Amanieu/parking_lot#85]
Seeing a compilation error of "this is an associated function, not a method"  when trying to call `upgrade()` on a `RwLockUpgradableReadGuard`. I've narrowed this down to parking_lot version 0.6.0; **version 0.5.5 compiles the below files with no error** (just irrelevant warnings about unused vars).

Was this breakage intentional? If so, what's the ergonomic way of calling `upgrade()` now? Frankly I have no idea how to call this method with >=0.6.0; even the help note from rustc isn't working out for me (maybe I'm dumb though).

Repro rust source file:

```rust
extern crate parking_lot;

use parking_lot::RwLock;

fn main() {
    let lock = RwLock::new(());
    let guard1 = lock.upgradable_read();
    let x = guard1.upgrade();
}
```

Cargo.toml:

```toml
[package]
name = "rusty-playground"
version = "0.1.0"

[dependencies]
parking_lot = "=0.6.3"
```

Compilation error:

```
$ cargo build
   Compiling rusty-playground v0.1.0 (file:///home/valloric/repos/rusty-playground)
error[E0599]: no method named `upgrade` found for type `lock_api::rwlock::RwLockUpgradableReadGuard<'_, parking_lot::raw_rwlock::ParkingLotRwLock, ()>` in the current scope
 --> src/main.rs:8:20
  |
8 |     let x = guard1.upgrade();
  |             -------^^^^^^^
  |             |      |
  |             |      this is an associated function, not a method
  |             help: use associated function syntax instead: `lock_api::rwlock::RwLockUpgradableReadGuard<'_, parking_lot::raw_rwlock::ParkingLotRwLock, ()>::upgrade`
  |
  = note: found the following associated functions; to be used as methods, functions must have a `self` parameter
  = note: the candidate is defined in an impl for the type `lock_api::rwlock::RwLockUpgradableReadGuard<'_, _, _>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `rusty-playground`.

To learn more, run the command again with --verbose.
```

**Comment by Valloric** [comment]
OK, I figured out how to call `upgrade()`:

```rust
extern crate parking_lot;
extern crate lock_api;

use parking_lot::RwLock;
use lock_api::RwLockUpgradableReadGuard;

fn main() {
    let lock = RwLock::new(());
    let guard1 = lock.upgradable_read();
    let x = RwLockUpgradableReadGuard::upgrade(guard1);
}
```

```toml
[package]
name = "rusty-playground"
version = "0.1.0"

[dependencies]
parking_lot = "0.6.3"
lock_api = "0.1.3"
```

This required an explicit dependency on `lock_api` and another `use` import. It's also very verbose.

Please tell me this isn't the intended way of using the API. :) The whole `lock_api` split is IMO hugely problematic because just navigating the docs is extremely difficult now ("which crate has the info I need?"); there's also an explosion of types with similar names. Knowing where to find the right method in the docs is very painful... but if this now also means that what used to be a simple method call requires this much ceremony, it's become rather difficult to swallow.

This is one of the most impressive crates in the Rust ecosystem but it's getting harder and harder to use. :(

**Comment by Amanieu** [comment]
You don't need to import the lock_api crate, you can use the re-exports from parking_lot (`use parking_lot::RwLockUpgradableReadGuard;`).

The reason this was changed to an associated method is to avoid conflicts with methods from `Deref`. This is actually specified in the [Rust API Guidelines](https://rust-lang-nursery.github.io/api-guidelines/predictability.html?highlight=deref#smart-pointers-do-not-add-inherent-methods-c-smart-ptr).

As for the documentation issue, I don't know of a good solution for this at moment.

**Comment by Valloric** [comment]
Yeah, I figured out that `use parking_lot::RwLockUpgradableReadGuard` is sufficient. Could this be mentioned in the docs somehow? It's not at all obvious how this method should be called; the rustc error is very confusing.

> The reason this was changed to an associated method is to avoid conflicts with methods from Deref. This is actually specified in the Rust API Guidelines.

The kind people on #rust pointed this out to me as well. I see why it's being done, I understand that it's necessary, but it just sucks in terms of UX.

> As for the documentation issue, I don't know of a good solution for this at moment.

This is the biggest issue IMO. I'll close this issue because it's not related to that, but you may want to track that separately. It's a substantial problem.

Thanks again for being open to feedback! :)
