### ISSUE TITLE
Async handling

### ISSUE THREAD

**Issue by Ekleog** [Amanieu/parking_lot#86]
This is a follow-up from https://github.com/Amanieu/parking_lot/issues/24, hopefully more explicit :)

So first, a disclaimer: I know literally nothing about the internals of `parking_lot`, and very little about mutexes.

What I'd be looking for is a way to have `parking_lot` mutexes play nicely with futures. What I mean by “play nicely” is:
 * It should never block the whole thread, only a task on the thread pool
 * It should return eg. a `Future<Item = MutexGuard<'a, T>>`

The second point can easily be implemented by wrapping `try_lock`, so that leaves the first point to handle.

My reflection on `parking_lot` internals (please tell me if it's wrong) is:
 * There is a “low-level” layer, which puts a thread to sleep, wake up a thread, etc.
 * Upon these building blocks, mutexes are built
 * Upon mutexes, guards are built

Most of the complexity would stand in the second layer above.

What I'm thinking is that, if the first layer could be swapped with an async-friendly layer (that would put a task to sleep instead of the whole thread, wake up a task, etc.), then I think it would become possible to reuse the biggest part of the code, that is in how mutexes are built on top of these primitives.

A way to do that may be to parameterize all `parking_lot` types on a helper trait that provides said functions, and static-dispatch on it, with type aliases for more convenience.

Now, as stated above, I know nothing about the internals of `parking_lot`, so I may completely be wrong in my analysis. Feel free to tell it to me if so :)

So, what do you think about this idea of splitting away the low-level task handling from the mutex building?

**Comment by Amanieu** [comment]
I don't think that simply parameterizing the lock types is sufficient: what you are suggesting (changing the return type from `MutexGuard` to `Future<Item = MutexGuard>`)  is actually a pretty significant API change.

The `lock_api` crate is designed to provide a high-level API on top of a basic raw mutex type (the top-most level from your description). While it might be possible to add support for futures to this, it would introduce a lot of complexity to what is already a very complex crate.

A bigger issue is that the mechanism used by `Future` to wake up a thread is very simple: you just call `wake()` on a `Waker` object that you obtain when the `Future` is polled. The `parking_lot_core` API is  much more advanced and allows for things like fairness guarantees, passing in tokens when parking/unparking, and callback which allow fine-grained control of how threads are woken up. The mutex algorithm in `parking_lot` (the middle level from your description) heavily relies on these features and most likely won't work without them.

My conclusion remains the same as in #24: you would be better off writing a new crate from scratch to provide mutexes that integrate with futures.

**Comment by Ekleog** [comment]
I'm sorry to have misexplained: I don't advocate to change the return type from `MutexGuard` to `Future<Output = MutexGuard>`, the sentence about wrapping `try_lock` was meant to indicate that a `parking_lot_async` crate could implement the returning `Future<Output = MutexGuard>` based on the `try_lock` provided by `parking_lot` :)

What I was thinking was mostly adding an implementation of `parking_lot_core::thread_parker` (not the whole `parking_lot_core`, as far as I understand) for a new runtime: instead of supporting Unix, Linux or Windows, it'd support futures executors. Only implementing at this module boundary would (I hope) make the implementation of an async-friendly mutex much easier than re-writing all the very complex code of `parking_lot_core` and `parking_lot`.

Now, I'm not really sure this would be easily doable: for instance, `ThreadParker::park()` and `park_until` would need to yield, which requires early-return, so maybe some adaptations further up the chain would be required too to propagate said early-return. However, from my outsider-who-actually-doesn't-know-of-what-he-is-speaking point of view, I currently think it'd be easier to patch `parking_lot` to support futures than to start one from scratch. because I'd place the boundary at the `parking_lot_core::thread_parker` level and not at the `parking_lot_core` level. (well, that and a `spinwait::thread_yield`, which would see a similar change in implementation)

Then, maybe what I'm saying doesn't make sense at all, because I don't know the internals of `parking_lot_core` at all and have very little experience implementing mutexes. Do you think it's currently the case?
