### ISSUE TITLE
Please release a 0.2.15 for parking-lot-core to include the rand bump from 0.4 to 0.5

### ISSUE THREAD

**Issue by mehcode** [Amanieu/parking_lot#88]
From the commit history I couldn't figure out why parking-lot is still depending on rand 0.4 ( on crates.io ) but [it is](https://github.com/rust-lang/crates.io-index/blob/master/pa/rk/parking_lot_core).

When you get time could you please release a new version for core that definitely has the rand bump?

**Comment by Amanieu** [comment]
Done.
