### ISSUE TITLE
Document minimum required Rust version policy

### ISSUE THREAD

**Issue by carllerche** [Amanieu/parking_lot#89]
A recent release of `parking_lot_core` increased the minimum required Rust version to 1.26. The commit was made ~3 months ago.

Would you mind documenting in the README what the policy is to increase the minimum required Rust version?

**Comment by Amanieu** [comment]
Oops, sorry about that, that was unintentional. I will yank that version.

**Comment by Amanieu** [comment]
parking_lot core 0.2.15 has been yanked and re-published as 0.3.0.

I also added a note in the README about the minimum Rust version.

**Comment by jonas-schievink** [comment]
Should this also be done for the `parking_lot` crate, since it depends on `parking_lot_core` 0.3.0?

**Comment by hawkw** [comment]
This issue isn't completely fixed --- since `parking_lot` 0.6.4 depends on `parking_lot_core` 0.3, that makes 0.6.3 -> 0.6.4 a breaking change on Rust 1.25.

**Comment by carllerche** [comment]
@Amanieu unfortunately, it looks like `parking_lot` itself bumped its dependency from 0.2 -> 0.3 which is how we are getting it pulled in.

**Comment by Amanieu** [comment]
Ah, I see what the problem is. `parking_lot` 0.6 was intended to bump the version requirement to 0.26, but that didn't happen since I forgot to publish an updated `parking_lot_core`.

If you require an older Rust version then you should use `parking_lot` 0.5 instead.

**Comment by carllerche** [comment]
Unfortunately, we already published ourselves w/ `parking_lot` 0.6.

The original issue still holds, it would be helpful to publish your policy with regards to minimum Rust version :)

**Comment by Amanieu** [comment]
I added a policy to the README. From this point the minimum Rust version is 1.26 and any change will require a major version bump.

**Comment by Amanieu** [comment]
FYI, the latest parking_lot now supports Rust 1.24. See #94
