### ISSUE TITLE
Cargo audit flags smallvec, recommends update to >=6.3

### ISSUE THREAD

**Issue by jackcmay** [Amanieu/parking_lot#95]
error: Vulnerable crates found!

ID:	 RUSTSEC-2018-0003
Crate:	 smallvec
Version: 0.2.1
Date:	 2018-07-19
URL:	 https://github.com/servo/rust-smallvec/issues/96
Title:	 Possible double free during unwinding in SmallVec::insert_many
Solution: upgrade to: >= 0.6.3 OR ^0.3.4 OR ^0.4.5 OR ^0.5.1

https://github.com/Amanieu/parking_lot/blob/c3ae283e59bcd5010e5420ef2678bdffeec82b03/core/Cargo.toml#L12

**Comment by Amanieu** [comment]
Well technically just specifying the version as "0.6" should be enough for Cargo to pick up the latest version, which includes the fix.

**Comment by jackcmay** [comment]
Agreed, are you opposed to changing it to 0.6.3?

**Comment by Amanieu** [comment]
I will accept a PR for it if anyone wants to write one.

**Comment by jackcmay** [comment]
Thanks for the attention, looks like Cargo audit is not flagging this instance and is instead flagging another project.
